### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'Session'

### ISSUE THREAD

**Issue by shizidushu** [microsoft/OLive#100]
Try to run https://github.com/microsoft/OLive/blob/master/notebook-tutorial/Convert_Models_with_OLive.ipynb

Got error: AttributeError: module 'tensorflow' has no attribute 'Session'

It seems related to https://github.com/microsoft/OLive/blob/master/olive/conversion/tensorflow_converter.py#L139

**Comment by shizidushu** [comment]
@leqiao-1 I got know Olive from https://onnxruntime.ai/docs/performance/tune-performance.html. I suggest update the readme of Live and the onnx doc to indicate OLive's compatibility with tensorflow.

**Comment by leqiao-1** [comment]
@shizidushu Sure, thanks for your suggest.
