### ISSUE TITLE
More details on the arguments

### ISSUE THREAD

**Issue by ahuvabec** [microsoft/OLive#103]
I was wondering if there is a more in depth documentation of what each argument does or how do the arguments operate?

**Comment by leqiao-1** [comment]
Hi @agrbhuvnesh 
Now all the documentation about the arguments are in this repo. 
If you want to know more details about any arguments, I can explain in this conversion.

**Comment by leqiao-1** [comment]
If you have any further concerns or questions, please reopen this issue.
