### ISSUE TITLE
whisper pipeline corrupting the model, unable to run on DML EP

### ISSUE THREAD

**Issue by khmyznikov** [microsoft/Olive#1031]
**Describe the bug**
input to the STFT node is not correct. The inputs are rank 2 [1, sample_len], when it should be rank 3 [1, sample_len, 1] for real valued data. The Pad operator needs to be updated accordingly as well, to know that the input is 3 dimensional, and pad the last dimension with 0s in the start and end. https://onnx.ai/onnx/operators/onnx__STFT.html

**Expected behavior**
Model correctly executes on DML + CPU EPs and fallback without errors.

**Olive config**
https://github.com/microsoft/Olive/tree/main/examples/whisper

**Comment by jambayk** [comment]
Closing since issue source is onnxruntime-extension and was resolved by https://github.com/microsoft/onnxruntime-extensions/pull/681.
