### ISSUE TITLE
import the unsafe code again

### ISSUE THREAD

**Issue by cckuailong** [microsoft/OLive#104]
here is the commit to the master. 
https://github.com/microsoft/OLive/commit/e3bb70414e4df7ab81ed356959d438982368484e

We can see, it cover the security fix.
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/10824150/178426832-f657261d-656b-48b1-bfe0-c76ab0faf2d7.png">

we can read arbitrary file, like /etc/passwd
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/10824150/178427066-d7f9356f-cd05-4959-a30c-1908428b0361.png">

**Comment by leqiao-1** [comment]
@cckuailong 
Thanks for reporting this issue.
However, flask.safe_join was removed since version 2.1.1
https://github.com/pallets/flask/issues/4516

**Comment by leqiao-1** [comment]
If you have any further concerns or questions, please reopen this issue.
