### ISSUE TITLE
[FR]: Finetuning QLoRA adapters and swapping

### ISSUE THREAD

**Issue by franperezlopez** [microsoft/Olive#1182]
### Proposal Summary

During Build 2024 presentation named "Create Generative AI experiences using Phi", there is a slide mentioning "finetuning Phi3 using QLoRA for 3 different skills" and "swapping QLoRA adapters". 
![image](https://github.com/microsoft/Olive/assets/1222398/b9d4ee61-471d-49b0-8a13-4996a7ca2de8)
I suppose this experiment was made using Olive, but I'm not able to find the source code. Can you help me? I like this approach and I'd love to dig into it. Thanks

### What component(s) does this request affect?

- [X] OliveModels
- [ ] OliveSystems
- [ ] OliveEvaluator
- [ ] Metrics
- [ ] Engine
- [ ] Passes
- [ ] Other

**Comment by jambayk** [comment]
Hi, 

You can check out this notebook for an example workflow https://github.com/microsoft/Olive/blob/main/examples/llama2/llama2_multilora.ipynb. 
I want to note that some of the related changes in [onnxruntime-genai](https://github.com/microsoft/onnxruntime-genai) model builder have not been checked in yet so the model you get out of this example is not the most optimized.
