### ISSUE TITLE
[Whisper] convert with FP32 running failed

### ISSUE THREAD

**Issue by Jay19751103** [microsoft/Olive#1207]
**Describe the bug**
Converted an mp3 file or wav file to text failed.

**To Reproduce**
Steps to reproduce the behavior.
python test_transcription.py  --audio_path d:\disc\converted.mp3 --predict_timestamps --language Japanese --config whispe
r_cpu_fp32.json
**Expected behavior**
Translate output text of audio file

**Olive config**
Add Olive configurations here.

**Olive logs**
Add logs here.
2024-06-21 15:37:47.9853878 [E:onnxruntime:, sequential_executor.cc:516 onnxruntime::ExecuteKernel] Non-zero status code returned while running ConstantOfShape node. Name:'/ConstantOfShape' Status Message: C:\a\_work\1\s\onnxruntime\core\framework\op_kernel.cc:83 onnxruntime::OpKernelContext::OutputMLValue status.IsOK() was false. Tensor shape cannot contain any negative value

**Other information**
 - OS: [e.g. Windows, Linux]
 - Olive version: [e.g. 0.4.0 or main]
 - ONNXRuntime package and version: [e.g. onnxruntime-gpu: 1.16.1]

**Additional context**

**Comment by trajepl** [comment]
Have you tried to upgrade the verion of Olive and onnxruntime?

**Comment by Jay19751103** [comment]
> Have you tried to upgrade the verion of Olive and onnxruntime?

I use tool to cut the audio file from 48s shorter than 30s. it can run now.

**Comment by jambayk** [comment]
Yes, 30 seconds is the maximum length of audio the whisper model can handle. Please refer to a comment I made in another related issue https://github.com/microsoft/Olive/issues/1108#issuecomment-2075824364

**Comment by xiaoyu-work** [comment]
Resolving.
