### ISSUE TITLE
[bug] Failed to perform inference on the optimized distil-large-v3 using the test_transcription.py

### ISSUE THREAD

**Issue by MrRace** [microsoft/Olive#1231]
I optimized the distil-large-v3 model using Olive:

Step 1:
```
python3 prepare_whisper_configs.py --model_name /share_model_zoo/LLM/distil-whisper/distil-large-v3/
```

Step 2:
```
python3 -m olive.workflows.run --config whisper_gpu_fp32.json --setup
```

Step 3:
```
python3 -m olive.workflows.run --config whisper_gpu_fp32.json 2> /dev/null
```

Then, I realized that the optimized model is still larger than 2GB. Since ONNX forcibly splits models larger than 2GB into two files: model_with_beam_search.onnx.data and model_with_beam_search.onnx,
I referred to the https://github.com/microsoft/Olive/blob/main/examples/whisper/test_transcription.py script to perform inference on the model, but encountered an error:
```
input_data = OnnxEvaluator.format_input(input_data, olive_model.get_io_config())
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ONNXModelHandler' object has no attribute 'get_io_config'. Did you mean: '_io_config'?
```

Even after changing it to:
```
input_data = OnnxEvaluator.format_input(input_data, olive_model._io_config())
```

It still throws an error:
```
input_data = OnnxEvaluator.format_input(input_data, olive_model._io_config())
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

How should I modify the test_transcription.py script to perform inference on the distil-whisper/distil-large-v3/ model optimized using the whisper_gpu_fp32.json configuration?

**Comment by jambayk** [comment]
it needs to be `olive_model.io_config` https://github.com/microsoft/Olive/blob/064e9a60f5cedfdb5a6f1b7f9434d4ce5a8396fe/examples/whisper/test_transcription.py#L122 

Can you try that change?

**Comment by MrRace** [comment]
@jambayk 
It still throws an error:
```
input_data = OnnxEvaluator.format_input(input_data, olive_model._io_config())

                                                        ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

**Comment by MrRace** [comment]
@jambayk Have you encountered the following problems?  `AttributeError: 'ONNXModelHandler' object has no attribute 'run_session'`

**Comment by trinhtuanvubk** [comment]
> @jambayk Have you encountered the following problems? `AttributeError: 'ONNXModelHandler' object has no attribute 'run_session'`

this is a weird bug @jambayk  . I have used some functions to test such as `dir(olive_model)` , `ONNXModelHandler.__dict__`. There is no `run_session` although `run_session` is implemeted inside `ONNXModelHandler`

- Quick fix for @MrRace : just replace `output = olive_model.run_session(session, input_data)` to `output = session.run(None, input_data)`

**Comment by jambayk** [comment]
The examples on the repo are updated to work with the latest code on main. Could you please pull the latest code and also install Olive from source https://microsoft.github.io/Olive/getstarted/installation.html#install-from-source

You could also checkout the tags for specific versions of Olive https://github.com/microsoft/Olive/tree/main/examples#important

**Comment by MrRace** [comment]
> The examples on the repo are updated to work with the latest code on main. Could you please pull the latest code and also install Olive from source https://microsoft.github.io/Olive/getstarted/installation.html#install-from-source
> 
> You could also checkout the tags for specific versions of Olive https://github.com/microsoft/Olive/tree/main/examples#important

Thanks a lot, it works
