### ISSUE TITLE
[FR]: Gather per-pass output logs

### ISSUE THREAD

**Issue by skywall** [microsoft/Olive#1269]
### Proposal Summary

I plan to use Olive via its Python interface inside my tool. There is currently no easy solution to gather all stdout/stderr outputs related to specic passes. In other words, I have no way to get all the outputs produced by the second step of the pipeline.

Outputs produced by Olive can be gathered by registering custom handler for "olive" logger via:
```python
olive_logger = logging.getLogger('olive')
olive_logger.addHandler(MyHandler())
```
But such an output will not contain all the logs produced by the pass itself - for example output produced by ONNXRuntime QDQQuantizer (used internally by OnnxStaticQuantization pass) will not be included.

### What component(s) does this request affect?

- [ ] OliveModels
- [ ] OliveSystems
- [ ] OliveEvaluator
- [ ] Metrics
- [ ] Engine
- [X] Passes
- [ ] Other

**Comment by xiaoyu-work** [comment]
Hi @skywall , you can add onnxruntime log to output by setting [`log_severity_level`](https://microsoft.github.io/Olive/overview/options.html#engine-information) to 1 in the config file. This default value is 3 so there is no onnxruntime log printed.

**Comment by xiaoyu-work** [comment]
Closing. Feel free to reopen this if you have more questions.
