### ISSUE TITLE
[Flux1] - Type parameter (T) of Optype (Einsum) bound to different types

### ISSUE THREAD

**Issue by saddam213** [microsoft/Olive#1287]
**Describe the bug**
Unable to convert Flux1-schnell transformer model to onnx format

**To Reproduce**
Run basic convert/optimize pass

**Olive logs**
Error: Type parameter (T) of Optype (Einsum) bound to different types (tensor(float16) and tensor(double) in node (/pos_embed/Einsum_2).'

**Other information**
 - OS: Windows 10
 - Olive version:  main
 - ONNXRuntime: onnxruntime-gpu: 1.18.1

**Additional context**
3 Einsum nodes in the converted model have a tensor with data of float64 but an input of flaot16, seems like a cast should be inserted?

All other Flux sub-modules have converted ok, just the unet/transformer model

**Comment by jambayk** [comment]
Hi, is the model a float16 model? If so, exporting float16 model is not well supported in torch export. Normally, we export in float32 and then run another pass to convert to fp16. 

can you try these two passes instead? 
```json
      "c": {
          "type": "OnnxConversion",
          "target_opset": 17,
          "torch_dtype": "float32"
      },
      "o": {
          "type": "OrtTransformersOptimization",
          "model_type": "unet",
          "opt_level": 0,
          "keep_io_types": false,
          "float16": true
      }
```

**Comment by saddam213** [comment]
Original model type is bfloat16

I have tried all combinations (bfloat16 and float16), all end with the same error on the Einsum nodes

Have tried both cuda and cpu(DirectML)

The model is 23GB with bfloat, so quite a challenge to fit on a device using float32

I have had pretty good success with other transformer models like SD3, they seem to convert without issue, however I realize flux is pretty new

Ill see if I can pickup some more RAM today and try from float32

**Comment by saddam213** [comment]
Managed to upgrade to 64GB of RAM and try float32, came out to a hefty 46GB...

unfortunately I have encountered the same error on the Einsum nodes, this time failing to cast float32 to float64

```Type Error: Type parameter (T) of Optype (Einsum) bound to different types (tensor(float) and tensor(double) in node (/pos_embed/Einsum_2).'```

Conversion completed without error so did optimization, however error occurs on loading model, on CPU or GPU (W7900 48GB)

How would I inject a cast for these inputs? is there a known way to do that?

**Comment by saddam213** [comment]
Managed to find a workaround by just updating the float64 tensors to bfloat after conversion, model seems to load now :)

**Comment by saddam213** [comment]
> > updating the float64 tensors to bfloat
> 
> before convert to onnx? cast float64 to float16?

After conversion you will need to update 3 nodes, `Einsum`, `Einsum_1`, and `Einsum_2` the weights for these nodes are `float64` so you will need to insert casts before and after.

![Image](https://github.com/user-attachments/assets/1681d441-744e-4f6d-a690-84445934a913)


Do not set the weights to `Float16`, it will ruin the quality of the Flux output

Here are some of the ONNX conversions:
https://huggingface.co/saddam213/Flux_dev-f16-onnx
https://huggingface.co/TensorStack/Flux_schnell-f32-onnx
https://huggingface.co/TensorStack/Flux_schnell-f16-onnx
