### ISSUE TITLE
[Bug]: ImportError: cannot import name 'load_model'

### ISSUE THREAD

**Issue by Pilaf4567** [microsoft/Olive#1406]
Hello !

I have the same error described here : [https://github.com/microsoft/Olive/issues/652](url)

Using this tutorial update : https://community.amd.com/t5/ai/updated-how-to-running-optimized-automatic1111-stable-diffusion/ba-p/630252

I tried the command of the last comment but that not solve the problem for me. Could you help me please ? Im kinda noob so sorry if i havnt give you enough information, feel free to ask me more details and i will update my message.
Sorry for my Bad english toi...

**Comment by xiaoyu-work** [comment]
Can you please paste your error message here?
