### ISSUE TITLE
About OnnxStaticQuantization

### ISSUE THREAD

**Issue by zz002** [microsoft/Olive#143]
Hi All
I use `OnnxStaticQuantization` to quantize an onnx model, and I intend to deploy the quantized model to the dpu later.
Due to the limitation of dpu, the parameter `y_scale/x_scale` of `QuantizeLinear/DequantizeLinear` in the expected quantization model belongs to `1/(2^n)`.For example `1, 0.5, 0.25, 0.125, ...`

As shown in the figure is a partial `QuantizeLinear/DequantizeLinear` ops screenshot of the current output.
![image](https://user-images.githubusercontent.com/75290391/229006137-93ef6e5b-6260-41ac-8116-1e65ed5ff653.png)

Is there any parameter or other way to solve this problem?

**Comment by trajepl** [comment]
From my understanding, in onnx static quantization with QDQ quantization format. The y_scale/x_scale of QuantizeLinear/DequantizeLinear should always be 1 which can make sure the model accuracy. 

Could you help introduce more about the value less than 1? Or introduce the framework which support this feature?

**Comment by zz002** [comment]
Sorry, maybe my formulation is wrong, the limit of dpu is
![image](https://user-images.githubusercontent.com/75290391/229705929-e9cdcbf0-44d0-4329-a961-a08fd5f720b9.png)

**Comment by trajepl** [comment]
IC, thanks for explaination. We do consider the similar case that which may come in next stage. But it mainly focus on to avoid to insert the quantization/dequantization pair for those node hold scale value > 1.

But if you want to quantize all nodes and limit their scale value to 1/(2^n), by now there is no flag for that I think. 
Maybe you can try to raise this requriement to onnxruntime quantization team. https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/quantization/quantize.py

They may have the experience on special EP for your dpu.

**Comment by trajepl** [comment]
https://github.com/microsoft/Olive/pull/265
