### ISSUE TITLE
import_module_from_file failed at /my_path

### ISSUE THREAD

**Issue by zz002** [microsoft/Olive#144]
Hi 
When I provide `script_dir=/my_path` to expect the program to search `user_script` under my `/my_path` path, but it only searches the current path`./`
https://github.com/microsoft/Olive/blob/main/olive/common/import_lib.py#L37
https://github.com/microsoft/Olive/blob/main/olive/common/import_lib.py#L12

**Comment by xiaoyu-work** [comment]
Hi @zz002, do you have any modules that are needed in your `user_script.py`? if you only need your `user_script.py`, you don't need to specify `script_dir`, but you can pass the path of your `user_script.py` only. Please check user_script [document](https://microsoft.github.io/Olive/tutorials/how_to_write_userscript.html#id1) for reference

**Comment by xiaoyu-work** [comment]
@zz002 do you still have any questions about this? If not, I will close this issue.
