### ISSUE TITLE
Convert-adapters method output file name error when given name has dot inside

### ISSUE THREAD

**Issue by liuyunms** [microsoft/Olive#1459]
**Describe the bug**
When the given output file name has ".",  generated file name only has chars before ".".
 
**To Reproduce**
olive convert-adapters --adapter_path Coldstart/Llama-3.1-8B-Instruct-Surfer-Dude-Personality --output_path adapters\Llama-3.1-8B-Instruct-Surfer-Dude-Personality --dtype float32
 
It will generate adapter name: Llama-3.onnx_adapter
 
**Expected behavior**
Should generate adapter name: Llama-3.1-8B-Instruct-Surfer-Dude-Personality.onnx_adapter
 
**Olive config**
 
**Olive logs**
(multilora_clearcache) D:\MultiLora>olive convert-adapters --adapter_path Coldstart/Llama-3.1-8B-Instruct-Surfer-Dude-Personality --output_path adapters\Llama-3.1-8B-Instruct-Surfer-Dude-Personality --dtype float32
Exported adapter weights to adapters\Llama-3.onnx_adapter
 
**Other information**
- OS: Windows
- Olive version: 0.7.0
- ONNXRuntime package and version: onnxruntime: 1.20
- Transformers package version: transformers 4.44
 
 
**Additional context**
Related to sample code of MultiLora https://github.com/natke/multilora
@natke

**Comment by jambayk** [comment]
Hi, this issue will be fixed once the linked PR gets merged. Thanks!
