### ISSUE TITLE
olive auto-opt does not generate genai_config.json when --provider option is given

### ISSUE THREAD

**Issue by natke** [microsoft/Olive#1471]
**Describe the bug**
Config required for runtime not generated

**To Reproduce**
`olive auto-opt -m meta-llama/Llama-3.1-8B-Instruct --adapter_path Coldstart/Llama-3.1-8B-Instruct-Surfer-Dude-Personality -o models\Llama-3-1-8B-Instruct-LoRA-dml --provider DmlExecutionProvider --precision int4` 

**Expected behavior**
Expect config to get generated

**Olive config**
No olive config

**Olive logs**
```
Loading HuggingFace model from meta-llama/Llama-3.1-8B-Instruct
Command succeeded. Output model saved to C:\Users\nakersha\Develop\samples\multilora\models\Llama-3-1-8B-Instruct-LoRA-dml
```

**Other information**
 - OS: Windows
 - Olive version: latest main
 - ONNXRuntime package and version: onnruntime-genai-directml: 0.5.0, onnxruntime-directml: 1.20
 - Transformers package version: transformers 4.44.0

**Additional context**

**Comment by jambayk** [comment]
Requires `--use_ort_genai` option to be provided when not using `--use_model_builder`. 

`--use_ort_genai` support was added in https://github.com/microsoft/Olive/pull/1473
