### ISSUE TITLE
onnx GPU optimization

### ISSUE THREAD

**Issue by heman-CL** [microsoft/Olive#1514]
Dear great authors, 

I've tried to use Olive to optimize FP32 models to FP16 ones. 
It infers faster under DML. However, when using CPU mode, it is slower than FP32. 

Is it normal? 

I've tried "peephole_optimizer"/"float16_conversion"/"session_params_tuning" passes. 
Moreover, I've tried "olive auto-opt -- " methods as well. 
Both of them are run slower than original FP32 onnx model under CPU. 

Could you please help comment it?  

Thanks

**Comment by xiaoyu-work** [comment]
FP16 is primarily designed for GPUs. If your CPU doesn't support FP16, running FP16 models might be slower due to the overhead of FP16 to FP32 emulation.

**Comment by xiaoyu-work** [comment]
Closing. Feel free to reopen if you have any questions.
