### ISSUE TITLE
Question: what about Nvidia Ada Fp8 support?

### ISSUE THREAD

**Issue by oscarbg** [microsoft/Olive#294]
Hi,
Just a question FP8 in new NV ada gpus it’ supported on DirectML and Olive?
If not any plans to support?
Assume it can bring another 2x speedup to stable diffusion sample?
Thanks..

**Comment by nbcsm** [comment]
Thanks for reaching to us.
@jstoecker to comment for DirectML EP plan.

**Comment by jstoecker** [comment]
Hi @oscarbg. FP8 is not something that DirectML supports at the moment, but we're keeping an eye on it.
