### ISSUE TITLE
The output is incorrect given a specific latent

### ISSUE THREAD

**Issue by KotomiHacker** [microsoft/Olive#298]
[latents.zip](https://github.com/microsoft/Olive/files/11560942/latents.zip)
latents.zip includes `latent1.npy` in fp32 type and `latent2.npy` in fp16 type.
The output with `Olive optmized model` is totally black when using `latent1` while it works with `latent2` .  I do did the data type conversion in the script. 
Besides, I also tested `latent1_fp32` with a common sd1.5 onnx fp16 model, it works as well. 
So, it looks like there is some other requirements for data range when using Olive optmized model?

Enviroment:  onnxruntime 1.15, Olive master, torch1.3
Script:
```
from diffusers import StableDiffusionOnnxPipeline
import numpy as np
pipe = StableDiffusionOnnxPipeline.from_pretrained(r".\Olive\examples\directml\stable_diffusion\models\optimized\runwayml\stable-diffusion-v1-5", provider="DmlExecutionProvider")
prompt = "a photo of an astronaut riding a horse on mars"
latents = np.load(r"latents.npy") .astype(np.float16)
h , w = 512, 512
image = pipe(prompt,height = h, width = w, num_inference_steps = 20
,  latents = latents
).images[0] 
image.save("mansion.png")
```

**Comment by trajepl** [comment]
I assume the repro steps should be:
1. You cloned our repo and run the stable diffusion example with `python stable_diffusion.py --optimize`. 
2. Then you have the model folder ready under `r".\Olive\examples\directml\stable_diffusion\models\optimized\runwayml\stable-diffusion-v1-5"`
3. So when you replace the `latent`, it worked well for fp16 weights but failed for fp32 weights.

Please correct me if the assumption is wrong.

But if so, I think the reason is that our example optimized the model from fp32 to fp16 already to speed up inferencing. 

You can change the flag of `fp16` to false and try again with fp32 latent weights.

![image](https://github.com/microsoft/Olive/assets/13343117/d4e46d57-e8c5-45ba-a167-f13afa63e7a1)
![image](https://github.com/microsoft/Olive/assets/13343117/19cd9892-7faa-4e9c-b6d3-85142151e940)

**Comment by KotomiHacker** [comment]
> I assume the repro steps should be:
> 
> 1. You cloned our repo and run the stable diffusion example with `python stable_diffusion.py --optimize`.
> 2. Then you have the model folder ready under `r".\Olive\examples\directml\stable_diffusion\models\optimized\runwayml\stable-diffusion-v1-5"`
> 3. So when you replace the `latent`, it worked well for fp16 weights but failed for fp32 weights.
> 
> Please correct me if the assumption is wrong.
> 
> But if so, I think the reason is that our example optimized the model from fp32 to fp16 already to speed up inferencing.
> 
> You can change the flag of `fp16` to false and try again with fp32 latent weights from step1(in above assumption).
> 
> ![image](https://user-images.githubusercontent.com/13343117/240868585-d4e46d57-e8c5-45ba-a167-f13afa63e7a1.png) ![image](https://user-images.githubusercontent.com/13343117/240868672-19cd9892-7faa-4e9c-b6d3-85142151e940.png)

Yes, your assumption for step 1&2 is right. For step 3, not sure what does it mean of replacing `latent`. Let's clarify this concept, `latent` can be considered as an input data as I used in the scirpt which is to get the same output even running several times. 
So, as an input data, I converted it into fp16 data type in the script, but why it cannot work? 

The second thing is I want to check is if I change the falg of `fp16` to false, the model wolud be fp32 model, right? However,  I also tested `latent_fp32` with a common sd1.5 onnx fp16 model, it works as well. `A common sd1.5 onnx fp16 model` is converted by the [scirpt ](https://github.com/huggingface/diffusers/blob/main/scripts/convert_stable_diffusion_checkpoint_to_onnx.py) with `fp16` flag on provided by diffuser.

**Comment by trajepl** [comment]
Yes, I meant that you replaced pre-generated latent noisy in original pipeline with your fixed one just as you said to ensure the output image is same for step 3.

Also I tried the huggingface convert script you mentioned, but it failed on fp16 onnx model with fp32 latent.
![image](https://github.com/microsoft/Olive/assets/13343117/0a822884-7024-4c76-91b0-390b7ea23748)
![image](https://github.com/microsoft/Olive/assets/13343117/0c453fa9-f42d-4746-822e-2e010d0fa74d)


[test.zip](https://github.com/microsoft/Olive/files/11572283/test.zip)

**Comment by KotomiHacker** [comment]
The error happens becuase you didn't successfully convert model into fp16, so runtime requires float tensor.
If you run the huggingface convert script for `fp16` flag, please make sure you have torch cuda version. Otherwise, the model cannot be converted into FP16, using fp32 instead. You can double check the binary size with your converted model whether it is half reduced.

**Comment by trajepl** [comment]
![image](https://github.com/microsoft/Olive/assets/13343117/c80b1301-fcde-4b61-85ea-910861f960f9)
Emm, the runtime requires float16 tensors, but we pass the fp32 tensors for latent.

Also I double checked that the model was converted successfully. 
You can found that the model size is half reduced compared with torch model. https://huggingface.co/runwayml/stable-diffusion-v1-5

![image](https://github.com/microsoft/Olive/assets/13343117/b21119b5-20d5-4d09-9165-68a67e609ed5)

**Comment by KotomiHacker** [comment]
Oh, sorry! looks like your script didn't did convert float32 to float16.
Check the script in my first comment.  `latents = np.load(r"latents.npy") .astype(np.float16)`

**Comment by jstoecker** [comment]
I'm not able to repro this with the latents.zip you attached:

```python
from diffusers import StableDiffusionOnnxPipeline
import numpy as np
from PIL import ImageStat
from PIL import Image

pipe = StableDiffusionOnnxPipeline.from_pretrained(
    r"models/optimized/runwayml/stable-diffusion-v1-5",
    provider="DmlExecutionProvider"
)

def test(latents_path):
    print(f"\nUsing {latents_path}")

    latents = np.load(latents_path)
    print(f"Latents data type before: {latents.dtype}")

    latents = latents.astype(np.float16)
    print(f"Latents data type after: {latents.dtype}")

    h, w = 512, 512
    prompt = "a photo of an astronaut riding a horse on mars"
    result = pipe(prompt, height=h, width=w, num_inference_steps=20, latents=latents)

    print(f"Passed Safety Checker: {not result.nsfw_content_detected[0]}")
    image = result.images[0]
    print(f"Median color RGB: {ImageStat.Stat(image).median}")

    image.save("mansion.png")


test("latents1.npy")
test("latents2.npy")
```

Output (note the median colors for both are nonzero):
```
Using latents1.npy
Latents data type before: float32
Latents data type after: float16
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:02<00:00,  7.93it/s]
Passed Safety Checker: True
Median color RGB: [157, 156, 156]

Using latents2.npy
Latents data type before: float16
Latents data type after: float16
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 14.51it/s]
Passed Safety Checker: True
Median color RGB: [184, 121, 80]
```

The generated images also look like the prompt (subpar quality given the 20 steps). A black output image typically means the safety checker failed.

Can you attach a [dxdiag](https://support.microsoft.com/en-us/windows/open-and-run-dxdiag-exe-dad7792c-2ad5-f6cd-5a37-bf92228dfd85) file?

**Comment by KotomiHacker** [comment]
@jstoecker Hi, thanks for the validatiopn. I just noticed there is some updated from olive main branch recently, so I use the latest branch to do the validation again and the results are good with latent_fp32.  What I tested before resulting in black image is  from jstoecker/directml_sd in commit id e954a82ead2c12be92b7b2f828055e9801017d22 on Apr 14. But anyway, I dump the didiag file here.
[DxDiag.txt](https://github.com/microsoft/Olive/files/11595315/DxDiag.txt)

In fact, I found an interesting thing is the performance of lastest optimized model is worse than before. Here is the detail on NV3090 card
|                                                                           | unet it/s |
| ------------------------------------------------------------------------- | --------- |
| jstoecker/directml_sd commit id: e954a82ead2c12be92b7b2f828055e9801017d22 | 9.56      |
| olive-ai[directml]0.2.1                                                   | 8.04      |
| latest branch                                                             | 8.04      |

**Comment by jstoecker** [comment]
There are a few things to consider when timing SD inference speed:
- The first inference is always slower, especially with GPU devices, because of caches at various levels. You typically ignore the first inference when benchmarking on GPU (or treat it as a separate metric).
- The script I shared above doesn't set everything needed for getting the best perf. You need to tell the ORT session that some tensor shapes aren't going to change between inferences so it can cache things even more aggressively.
- In your dxdiag.txt, I see that you have NVIDIA's 516.94 driver. Make sure to upgrade to [532.03](https://www.nvidia.com/Download/driverResults.aspx/204969/en-us/) or newer, as [they added some perf improvements in newer releases](https://blogs.nvidia.com/blog/2023/05/23/microsoft-build-nvidia-ai-windows-rtx/).

I did a quick test and optimized the models with commit e954a82 and compared them with v0.2.1 using the following script. Note the free dimension overrides (static dims), which allow further runtime optimization.

```python
from diffusers import OnnxStableDiffusionPipeline
import onnxruntime as ort

def test(model_path, static_dims):
    print(f"Model = {model_path}, Static Dimensions = {static_dims}")

    batch_size = 1
    num_steps = 20
    h, w = 512, 512
    prompt = "a photo of an astronaut riding a horse on mars"

    sess_options = ort.SessionOptions()
    sess_options.enable_mem_pattern = False
    if static_dims:
        sess_options.add_free_dimension_override_by_name("unet_sample_batch", batch_size * 2)
        sess_options.add_free_dimension_override_by_name("unet_sample_channels", 4)
        sess_options.add_free_dimension_override_by_name("unet_sample_height", 64)
        sess_options.add_free_dimension_override_by_name("unet_sample_width", 64)
        sess_options.add_free_dimension_override_by_name("unet_time_batch", 1)
        sess_options.add_free_dimension_override_by_name("unet_hidden_batch", batch_size * 2)
        sess_options.add_free_dimension_override_by_name("unet_hidden_sequence", 77)

    pipe = OnnxStableDiffusionPipeline.from_pretrained(
        model_path,
        provider="DmlExecutionProvider",
        sess_options=sess_options
    )

    for i in range(10):
        pipe(prompt, height=h, width=w, num_inference_steps=num_steps)


ort.set_default_logger_severity(3)
test(model_path="S:/test/optimized_with_olive_0.2.1", static_dims=False)
test(model_path="S:/test/optimized_with_olive_0.2.1", static_dims=True)
test(model_path="S:/test/optimized_with_e954a82ea", static_dims=False)
test(model_path="S:/test/optimized_with_e954a82ea", static_dims=True)
```

With an RTX 3090:
```
Model = S:/test/optimized_with_olive_0.2.1, Static Dimensions = False
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:02<00:00,  7.93it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 14.60it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 14.81it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 14.68it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 14.30it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 14.48it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 14.22it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 14.34it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 14.36it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 14.53it/s]
Model = S:/test/optimized_with_olive_0.2.1, Static Dimensions = True
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 17.95it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 23.48it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 23.69it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 23.68it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 24.19it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 22.98it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 22.55it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 23.84it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 23.15it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 24.00it/s]
Model = S:/test/optimized_with_e954a82ea, Static Dimensions = False
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:02<00:00,  8.87it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 18.49it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 18.89it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 18.70it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 18.47it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 18.29it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 18.49it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 17.69it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 18.53it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 18.75it/s]
Model = S:/test/optimized_with_e954a82ea, Static Dimensions = True
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:01<00:00, 20.57it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 24.07it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 23.74it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 24.27it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 24.23it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 24.39it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 23.46it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 23.97it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 24.42it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 24.39it/s]
```

When disabling static dims, the results are similar to what you observed with first inference. It is interesting that the older versions are faster _without_ static shapes, and maybe just a tad with static dims. I would say the difference is significant with static dims though. I think this may be related to disabling some fusions that we didn't believe had any effect on performance, so I'll look a bit more next week.
