### ISSUE TITLE
Optimizing Fail (AMD CPU)

### ISSUE THREAD

**Issue by Bogit11** [microsoft/Olive#301]
I get a Fail when running the Optimizing command and get an AMD Bug Report Tool pop up (Driver timeout).
My Laptop has NVIDIA RTX 3070 Max-Q and an AMD CPU 

Copy of the Error: 

[WARNING] [engine.py:307:run] Failed to run Olive on gpu-dml: [ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\ExecutionProvider.cpp(896)\onnxruntime_pybind11_state.pyd!00007FFB7134FE91: (caller: 00007FFB713508BF) Exception(2) tid(4ac4) 887A0006 The GPU will not respond to more commands, most likely because of an invalid command passed by the calling application.

**Comment by nbcsm** [comment]
Thanks for reporting the issue.
@jstoecker for DirectML.

**Comment by jstoecker** [comment]
Hi @Bogit11. 
- Can you create a [dxgdiag trace](https://support.microsoft.com/en-us/windows/open-and-run-dxdiag-exe-dad7792c-2ad5-f6cd-5a37-bf92228dfd85) and attach it to this issue?
- Where in the optimization process do you see this error? The full output would be helpful to further narrow it down.
Thanks!

**Comment by xiaoyu-work** [comment]
Hi @Bogit11, are you still facing this issue?

**Comment by Bogit11** [comment]
I'm sorry for abandoning the submission!
No, I'm unable to recreate it, instead I'm was getting another problem so i decided to leave it.
Sorry ;(
