### ISSUE TITLE
I don't see a difference on GTX 1080

### ISSUE THREAD

**Issue by MastaDan9** [microsoft/Olive#306]
I have gone through all the steps described in examples\directml\stable_diffusion. 
I also installed the latest Nvidia drivers.
Launched marked --optimizer on the standard stable-diffusion-v1-5 model. After Optimizing the ONNX pipeline, I launched with the note "stable_diffusion.py --num_inference_steps 50 --num_images 1", it took me 24-26 seconds to generate, but without ONNX, I also get 24-26 seconds. Shouldn 't there be acceleration ?

![image](https://github.com/microsoft/Olive/assets/7467926/c881448f-5279-4389-8330-241d8b11b246)

**Comment by jstoecker** [comment]
Hi @MastaDan9. The NVIDIA improvements require RTX GPUs with tensor cores (outlined in this [DirectX post](https://devblogs.microsoft.com/directx/dml-stable-diffusion/) and [NVIDIA post](https://blogs.nvidia.com/blog/2023/05/23/microsoft-build-nvidia-ai-windows-rtx/)). The GTX cards do not have tensor cores, unfortunately, so you should not expect to see the same performance improvement.

**Comment by Dampfinchen** [comment]
> Hi @MastaDan9. The NVIDIA improvements require RTX GPUs with tensor cores (outlined in this [DirectX post](https://devblogs.microsoft.com/directx/dml-stable-diffusion/) and [NVIDIA post](https://blogs.nvidia.com/blog/2023/05/23/microsoft-build-nvidia-ai-windows-rtx/)). The GTX cards do not have tensor cores, unfortunately, so you should not expect to see the same performance improvement.

Are RTX 20 series GPUs also benefitting from these improvements? This is pretty confusing as in the blog post Microsoft mentions RTX 30 and 40 series support, but Nvidia in their own blog post states all RTX GPUs are supported. RTX 20 series have tensor cores as well, so they should benefit from it as well?

**Comment by jstoecker** [comment]
> Are RTX 20 series GPUs also benefitting from these improvements?

I just tested with an RTX 2080, and the 20 series cards are also benefitting from the 532.03 NVIDIA driver.

It's a holiday weekend in the US right now, but we'll update the post to reflect this when people are back next week. Thanks for pointing this out. @JacquesvanRhynMSFT FYI
