### ISSUE TITLE
I don't get the expected result

### ISSUE THREAD

**Issue by Unuse1ess** [microsoft/Olive#307]
### What happened?

I followed the instructions in examples\directml\stable_diffusion, and I also updated the nvidia driver. But its running speed is much worse than the one from [https://github.com/AUTOMATIC1111/stable-diffusion-webui](url).
It seems that it is running on my integrated graphic card.
<img width="750" alt="WeChat Screenshot_20230527225333" src="https://github.com/microsoft/Olive/assets/62944944/dd4c0a7c-8a58-40c1-b346-a461856a1f93">

<img width="1256" alt="WeChat Screenshot_20230527223333" src="https://github.com/microsoft/Olive/assets/62944944/2802e684-64d9-4254-a073-ec77c08ed286">

### Version?

OS: win11 22h2, os build 22621.1778
python: 3.10.11
nvidia driver: 532.03 (rtx3070ti laptop)
intel graphic driver: 31.0.101.4338

**Comment by jstoecker** [comment]
Thanks. This is a usability issue that we're planning to address in the next release of onnxruntime-directml.

Laptops with both integrated and discrete GPUs will default to the _power saving_ option (i.e. integrated GPU). We plan to add a Python API to onnxruntime-directml to choose between _power saving_ and _high performance_ programmatically; for now, however, you'll have to go through Windows settings to choose your preference:

- Navigate to Settings > Display > Graphics,
- Click _Browse_ under _Custom options for apps_
- Enter the path to your python.exe (in screenshot below I'm using one of my conda environments)
- Choose _High performance_

![image](https://github.com/microsoft/Olive/assets/3835701/886e6b46-c245-46a4-b852-c54e4a742446)

**Comment by xiaoyu-work** [comment]
@Unuse1ess Do you need more help from us? Can I close this issue?

**Comment by guotuofeng** [comment]
close the stale issue
