### ISSUE TITLE
[Bug]: Error converting whisper model to ORT

### ISSUE THREAD

**Issue by jwanga** [microsoft/Olive#340]
### What happened?

I can successfully convert whisper to onnx with the following:

```
python prepare_whisper_configs.py
python -m olive.workflows.run --config whisper_cpu_int8.json --setup
python -m olive.workflows.run --config whisper_cpu_int8.json 2> /dev/null
```

However when I attempt to convert the generated onyx model to ORTwith the following:
```
python -m onnxruntime.tools.convert_onnx_models_to_ort models/whisper_cpu_int8_cpu-cpu_model.onnx
```

I get this error:

```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /Users/username/Development/Olive/examples/whisper/models/whisper_cpu_int8_cpu-cpu_model.onnx failed:Fatal error: ai.onnx.contrib:BpeDecoder(-1) is not a registered function/op
```

### Version?

0.2.1

**Comment by guotuofeng** [comment]
@jwanga, would you please install https://github.com/microsoft/onnxruntime-extensions and pass the get_library_path() as the arguments like?:
 convert_onnx_models_to_ort.py custom_op_library CUSTOM_OP_LIBRARY

Please let us know if it doesn't work.

**Comment by jwanga** [comment]
That worked. Thank you, @guotuofeng
