### ISSUE TITLE
Performance Tuning from previous step is not loaded properly

### ISSUE THREAD

**Issue by BharathJaina** [microsoft/OLive#37]
While executing performance tuning `with model converted from the previous step` from Web Application: 

Getting following Error:
**`Failed to load model because protobuf parsing failed.`**

Is anyone facing this issue?

I had resolved it by Modifying the line 173:
```
 if (not model_name == ""):
        json_data['model'] = model_name
```

**Comment by liuziyue** [comment]
Thank you for pointing this out. This issue is fixed by #41
