### ISSUE TITLE
[FR]: Make vitis-ai quantization compatible with ORT 1.16.0+

### ISSUE THREAD

**Issue by jambayk** [microsoft/Olive#382]
### Proposal Summary

Vitis ai code uses some functions that are not available in ORT 1.16.0 is currently in development. Refer to https://github.com/microsoft/Olive/pull/380 for more details. 

### What component(s) does this request affect?

- [ ] OliveModels
- [ ] OliveSystems
- [ ] OliveEvaluator
- [ ] Metrics
- [ ] Engine
- [X] Passes
- [ ] Other

**Comment by jambayk** [comment]
@sheng-xiao FYI

**Comment by sheng-xiao** [comment]
@jambayk  See https://github.com/microsoft/Olive/pull/385 for the fix, thanks.
