### ISSUE TITLE
[Bug]: Update dependencies for demo Diffusion

### ISSUE THREAD

**Issue by contentis** [microsoft/Olive#421]
### What happened?

Using a clean enviornment based off Python 3.10, the default version of pydantic is 2.x which is not compatible with Olives current implementation. 

```
  File "...\envs\olive\lib\site-packages\pydantic\_internal\_model_construction.py", line 290, in inspect_namespace
    raise TypeError("To define root models, use `pydantic.RootModel` rather than a field called '__root__'")
TypeError: To define root models, use `pydantic.RootModel` rather than a field called '__root__'
```

pydantic==1.10 seems to be the sweetspot and I would recomment adding this to the requirements.txt

### Version?

0.2.1 with directml

**Comment by guotuofeng** [comment]
https://github.com/microsoft/Olive/pull/392 should already fix this issue
