### ISSUE TITLE
[Bug]: InferenceSessionConfiguration does not exist

### ISSUE THREAD

**Issue by sergiosolorzano** [microsoft/Olive#473]
### What happened?

I build onnx model using the example (whisper_cpu_int8.json) and I get correct results when I run python transcribe.py

However when I take the code to run on .net6.0 in VS2022 in a win11 environment, the generated code does not work: InferenceSessionConfiguration is unknown

I have installed Microsoft.ML.OnnxRuntime v 1.14.0 
<img width="1627" alt="image" src="https://github.com/microsoft/Olive/assets/24430655/2a2e280f-5ff8-4e7c-bed9-7fc2be1d176b">

I copied the code into this VS2022 project: /home/sergio/PythonWorkspace/whisper/Olive/examples/whisper/models/SampleCode/ONNXModel/cs/code_sample.cs

<img width="1247" alt="image" src="https://github.com/microsoft/Olive/assets/24430655/556e4bbb-b6f3-4ed2-93b6-2d514d3b5078">

### Version?

I'm using the Main branch, tag v0.2.1

**Comment by guotuofeng** [comment]
@xiaoyu-work

**Comment by xiaoyu-work** [comment]
Looking at this.

**Comment by sergiosolorzano** [comment]
thank you @xiaoyu-work , it references successfully
