### ISSUE TITLE
[Bug]: Error Node (BeamSearch_node) has input size 12 not in range [min=5, max=10].

### ISSUE THREAD

**Issue by sergiosolorzano** [microsoft/Olive#477]
### What happened?

I have tried with python 3.10 and 3.11. I create a conda env for this.

For example, I first clone the Olive repo and switch branch git checkout tags/v0.2.0 (i tried them all)
cd Olive
create conda env for python 3.11
python -m pip install .

Then in examples/whisper:
python -m pip install -r requirements.txt
python -m pip uninstall -y onnxruntime ort-nightly
python -m pip install ort-nightly --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/

Throws error:
```
(env_olive311) sergio@Ubuntu-2204-oai:~/PythonWorkspace/Olive/examples/whisper$ python prepare_whisper_configs.py --model_name openai/whisper-tiny.en
Traceback (most recent call last):
  File "/home/sergio/PythonWorkspace/Olive/examples/whisper/prepare_whisper_configs.py", line 231, in <module>
    main()
  File "/home/sergio/PythonWorkspace/Olive/examples/whisper/prepare_whisper_configs.py", line 39, in main
    whisper_model = get_ort_whisper_for_conditional_generation(args.model_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sergio/anaconda3/envs/env_olive311/lib/python3.11/site-packages/olive/hf_utils.py", line 59, in get_ort_whisper_for_conditional_generation
    decoder = WhisperDecoder(model, None, model.config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WhisperDecoder.__init__() takes 3 positional arguments but 4 were given
(env_olive311) sergio@Ubuntu-2204-oai:~/PythonWorkspace/Olive/examples/whisper$ 
```

-------------------
If I manage to build it cloning without changing tag and building with python 3.10 doing the same process, I get the error below when using the model in Microsoft's demo https://github.com/onnxruntime/Whisper-HybridLoop-Onnx-Demo/tree/main/AudioNoteTranscription

OnnxRuntimeException: [ErrorCode:InvalidGraph] Load model from C:/AR-VR-Github/UnitySentisStableDiffusion-And-Whisper/Assets/StreamingAssets/whisper/model.onnx failed:This is an invalid model. In Node, ("BeamSearch_node", BeamSearch, "com.microsoft", -1) : ("log_mel": tensor(float),"max_length": tensor(int32),"min_length": tensor(int32),"num_beams": tensor(int32),"num_return_sequences": tensor(int32),"length_penalty": tensor(float),"repetition_penalty": tensor(float),"","","","","",) -> ("sequences",) , Error Node (BeamSearch_node) has input size 12 not in range [min=5, max=10].
Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess (System.IntPtr nativeStatus) (at <36441e0316944e7eb9fd86bf4a9a5a82>:0)
Microsoft.ML.OnnxRuntime.InferenceSession.Init (System.String modelPath, Microsoft.ML.OnnxRuntime.SessionOptions options, Microsoft.ML.OnnxRuntime.PrePackedWeightsContainer prepackedWeightsContainer) (at <36441e0316944e7eb9fd86bf4a9a5a82>:0)
Microsoft.ML.OnnxRuntime.InferenceSession..ctor (System.String modelPath, Microsoft.ML.OnnxRuntime.SessionOptions options) (at <36441e0316944e7eb9fd86bf4a9a5a82>:0)

### Version?

I tried 0.2.1, 0.2.0,0.1.0
Python 3.10, 3.11
Ubuntu 23.04 - lunar

Since this involves both repos I have posted at https://github.com/onnxruntime/Whisper-HybridLoop-Onnx-Demo/issues/2

**Comment by jambayk** [comment]
Hi, this looks like a version mismatch between the onnxruntime used to create the model in Olive and the onnxruntime version used for inference in the demo. 

The current nightly version has moved much further ahead than what it was when the tag 0.2.0 was created. 

Can you try creating the model using the latest branch but not installing onnxruntime-nightly? Just install `requirements.txt` which installs the latest stable versions `onnxruntime` and `onnxruntime-extension` (these were the nightly versions when the tag was created).

**Comment by sergiosolorzano** [comment]
Hi @jambayk I tried without installing ort-nightly then onnxruntime is not installed: ModuleNotFoundError: No module named 'onnxruntime'

These are the steps I followed, python3.11:

- conda create --name env_olive311 python=3.11 and activate
- cd /home/sergio/PythonWorkspace/Olive
- git checkout tags/v0.2.0
- python -m pip install .
- python -m pip install -r requirements.txt
- cd examples/whisper
- python prepare_whisper_configs.py --model_name openai/whisper-tiny.en

`(env_olive311) sergio@Ubuntu-2204-oai:~/PythonWorkspace/Olive/examples/whisper$ python prepare_whisper_configs.py --model_name openai/whisper-tiny.en
Traceback (most recent call last):
  File "/home/sergio/PythonWorkspace/Olive/examples/whisper/prepare_whisper_configs.py", line 11, in <module>
    from onnxruntime.transformers.models.t5.past_helper import PastKeyValuesHelper
ModuleNotFoundError: No module named 'onnxruntime'
`

What version of onnxruntime works with tag 0.2.0 or 0.2.1? Python 3.11 ok or need 3.10?

**Comment by jambayk** [comment]
Oh I assumed you were on the `main` branch where the `requirements.txt` file has the onnxruntime and onnxruntime-extensions versions in it. https://github.com/microsoft/Olive/blob/main/examples/whisper/requirements.txt#L2C1-L3C30
Please install the following too if you are on one of the release tags:
```
onnxruntime>=1.15.0
onnxruntime-extensions>=0.8.0
```

**Comment by sergiosolorzano** [comment]
Thanks a lot @jambayk, yes that was my bad, sorry for confusing you.

I run it from main (no tag checkout) and I didn't run ort-nightly either.

I tried with Python 3.11 but had errors installing installing from source onnxruntime-extensions 0.8.0 and latest cr. With Python 3.10 all the required packages are there from the get-go as you said and works great!

Thank you so much for your help !
