### ISSUE TITLE
[Bug]: No way to specify config for OpenVINO inference

### ISSUE THREAD

**Issue by akarym-sl** [microsoft/Olive#560]
### What happened?

In the `prepare_session` method of `class OpenVINOModel(OliveModel)` in `olive.model.__init__.py` the `inference_settings `argument is not used. 
It could be passed as the `config` argument of `ie.compile_model` , i.e., `compiled_model = ie.compile_model(model=model_pot, device_name=device.upper(), config=inference_settings)` or  `compiled_model = ie.compile_model(model=model_pot, device_name=device.upper(), config=inference_settings["config"])`

### Version?

0.3.1

**Comment by guotuofeng** [comment]
@xiaoyu-work

**Comment by xiaoyu-work** [comment]
@akarym-sl I'm not sure what kind of config is supported for openvino `compile_model` api. [Openvino documentation](https://docs.openvino.ai/2022.3/api/ie_python_api/_autosummary/openvino.runtime.Core.html#openvino.runtime.Core.compile_model) doesn't have details. Do you know any documentation that specifies what is `config` here?

**Comment by akarym-sl** [comment]
@xiaoyu-work To be honest, the only config parameter that I have used is CPU_THREADS_NUM that I took from [this issue](https://github.com/openvinotoolkit/openvino/issues/11740), where @brmarkus gives a link to the  [documentation on PluginConfigParams](https://docs.openvino.ai/2022.3/namespaceInferenceEngine_1_1PluginConfigParams.html#details-namespace-inference-engine-1-1-plugin-config-params). This can be a starting point!

**Comment by xiaoyu-work** [comment]
@akarym-sl Another reason that it is not added here is this inference setting is mainly tuned for onnx model with onnxruntime. I don't think that could be help too much with openvino IR model.

**Comment by xiaoyu-work** [comment]
Closing as no action item.
