### ISSUE TITLE
[Bug]: whisper gpu does not consume gpu resources

### ISSUE THREAD

**Issue by jsoto-gladia** [microsoft/Olive#571]
### What happened?

After running the command (for whisper tiny multilingual): 
```bash
python test_transcription.py --config whisper_gpu_fp32.json 
```

and I change the test_transcription to be gpu resource intensive:
```bash
num_iterations = 100000
    for i in range(num_iterations):
        output = session.run(None, input)
```

howevever no gpu ressources are used:
<img width="1270" alt="image" src="https://github.com/microsoft/Olive/assets/102920976/98b50212-9f4a-4097-b43e-358deb260857">

Can you help me out ?

P.S by the way to make it work for gpu and needed to change the two following lines:
[here](https://github.com/microsoft/Olive/blob/3f760afede9e2081af942ecd9834c7b4dc9cc931/examples/whisper/test_transcription.py#L70) -> from '_cpu-cpu_model.json' to '_gpu-cuda_model.json'
[here] from (https://github.com/microsoft/Olive/blob/3f760afede9e2081af942ecd9834c7b4dc9cc931/examples/whisper/test_transcription.py#L97) from 'cpu' to 'gpu'

### Version?

main

**Comment by jambayk** [comment]
Thanks for bring this up! This PR https://github.com/microsoft/Olive/pull/563 should address this too. I just added a commit to address the `output_model_json_path` issue.
