### ISSUE TITLE
[Bug]: `ActivationSymmetric` default is not enforced in Vitis AI quantizer

### ISSUE THREAD

**Issue by fxmarty** [microsoft/Olive#622]
### What happened?

Hi, I noticed that the default in the docstring for [`ActivationSymmetric`](https://github.com/microsoft/Olive/blob/a46fdf210dfca121c17776c1d280b5cc6b0778d1/olive/passes/onnx/vitis_ai/quantize.py#L107) seem to be unforced nowhere in the code for Vitis AI quantizer.

Moreover, running quantization with Olive & running the quantizer model on Ryzen AI IPU, it appears symmetric weights are required, with the follow logs during compilation:
```
W20230929 19:30:42.923205 31228 to_xir_ops_pass.cpp:389] cancal xir conversion ,  int8 data_type only support zero_point is 0. this zero_point is: -12, @65 [/transformer/h.0/attn/c_attn/Reshape_output_0_QuantizeLinear_Output:(ty=3,shape=[128,32])] QuantizeLinear [/transformer/h.0/attn/c_attn/Reshape_output_0:(ty=1,shape=[128,32]),ortshared_1_0_1_2_token_402:(ty=1,shape=[]),/transformer/h.0/ln_1/Add_1_output_0_zero_point:(ty=3,shape=[])]
```
I wonder if `ActivationSymmetric=True `should always be enforced when using `enable_dpu=False`?

Thank you!

### Version?

Olive main
onnxruntime-vitisai & voe installed through `voe-4.0-win-amd64` prebuilt wheels.

**Comment by xiaoyu-work** [comment]
Hi @sheng-xiao , can you please take a look at this?

**Comment by ChaoLi-AMD** [comment]
Hi @fxmarty , the Ryzen AI IPU only supports symmetric activations and weights. So, the log showed 'int8 data_type only support zero_point is 0'. When using enable_dpu=False, ActivationSymmetric is not mandatory. When using enable_dpu=True, you need to set ActivationSymmetric to True.

**Comment by fxmarty** [comment]
Thank you @ChaoLi-AMD. I should have a double check at which config I was using exactly.

This issue is about quantizing with `enable_dpu=False`, `PowerOfTwoMethod`, and still having asymmetric zero point contrary to what the documentation that I linked indicates and contrary to what Vitis AI EP for Ryzen AI expects (symmetric quantization).

> When using enable_dpu=False, ActivationSymmetric is not mandatory

I would expect the contrary given that Ryzen AI IPU only supports symmetric activations and weights? Or if the default is `ActivationSymmetric=True`, it should be enforced somewhere. I did not find it in the code base.

**Comment by ChaoLi-AMD** [comment]
> Thank you @ChaoLi-AMD. I should have a double check at which config I was using exactly.
> 
> This issue is about quantizing with `enable_dpu=False`, `PowerOfTwoMethod`, and still having asymmetric zero point contrary to what the documentation that I linked indicates and contrary to what Vitis AI EP for Ryzen AI expects (symmetric quantization).
> 
> > When using enable_dpu=False, ActivationSymmetric is not mandatory
> 
> I would expect the contrary given that Ryzen AI IPU only supports symmetric activations and weights? Or if the default is `ActivationSymmetric=True`, it should be enforced somewhere. I did not find it in the code base.

Oh, if you want to use Vitis AI EP for Ryzen AI, you need symmetric activations and weights. You should set enable_dpu=True and ActivationSymmetric=True. ActivationSymmetric=True should always be enforced when using enable_dpu=True.

**Comment by guotuofeng** [comment]
@fxmarty, did @ChaoLi-AMD answer your questions? could I close this thread?

**Comment by fxmarty** [comment]
@guotuofeng thank you you can close!
