### ISSUE TITLE
[Bug]: Vitis AI quantizer with symmetric uint8 activation wrongfully hard-codes `zero_point=0`

### ISSUE THREAD

**Issue by fxmarty** [microsoft/Olive#623]
### What happened?

Hi,

with the following config

```
        "vitis_ai_quantization": {
            "type": "VitisAIQuantization",
            "disable_search": true,
            "config": {
                "calibrate_method":"NonOverflow",
                "quant_format":"QDQ",
                "ActivationSymmetric": true,
                "activation_type":"QInt8",
                ...
            }
        }
```

it appears that the zero point for activations is set to 0 instead of 128. Using `"activation_type":"QUInt8"` solves the issue (still 0, but rightfully this time).

It is probably a tiny bug (need to check on activation being signed or not).

Thank you!

### Version?

main

**Comment by xiaoyu-work** [comment]
Hi @sheng-xiao , can you please take a look at this?

**Comment by ChaoLi-AMD** [comment]
Hi @fxmarty , when you use the Qint8 data type and also set ActivationSymmetric to true, it represents a range of -127 to 127, so the zero point (zp) is typically set to 0.

**Comment by fxmarty** [comment]
Thank you @ChaoLi-AMD I must have been sleeping writing this issue. Rereading it,

> Using "activation_type":"QUInt8" solves the issue (still 0, but rightfully this time).

seem to be the issue. I will double check and keep you up.

**Comment by jambayk** [comment]
@fxmarty Is this issue still open or resolved?

**Comment by fxmarty** [comment]
@jambayk I'll double check ASAP and update  you.

**Comment by guotuofeng** [comment]
close this issue since it is pretty stale.
