### ISSUE TITLE
Mlperf_loadgen

### ISSUE THREAD

**Issue by AugustIndal** [microsoft/OLive#63]
Had to run "`pip install --extra-index-url https://olivewheels.azureedge.net/test mlperf_loadgen`" to run this tutorial. `https://github.com/microsoft/OLive/blob/master/notebook-tutorial/Optimize_ONNX_Models_Throughput_with_OLive.ipynb`

Missing module when running 
`from olive.optimize import optimize`

**Comment by leqiao-1** [comment]
@AugustIndal Thanks for reporting this issue. We have fixed it.
