### ISSUE TITLE
[FR]: quantize a fine-tuned model

### ISSUE THREAD

**Issue by marouanetalaa** [microsoft/Olive#640]
### Proposal Summary

Is it possible to generate a quantized model from a fine-tuned whisper model (fine-tuned by huggingface libraries ) ?

### What component(s) does this request affect?

- [ ] OliveModels
- [ ] OliveSystems
- [ ] OliveEvaluator
- [ ] Metrics
- [ ] Engine
- [ ] Passes
- [ ] Other

**Comment by marouanetalaa** [comment]
I am referring to whisper in examples

**Comment by jambayk** [comment]
Hi, do you have an example of a fine-tuned model? Is it already on the huggingface hub? 
If so, you can directly run the example using the model-id 
`python prepare_whisper_configs.py --model_name <model-id>`

**Comment by marouanetalaa** [comment]
Instead of pushing to the hub I did it locally with

```
model = WhisperForConditionalGeneration.from_pretrained("./model/")

torch.save(model.state_dict(), "./final/model.en")
```

and then `python prepare_whisper_configs.py --model_name "./final/model.en"`
to get the config files, but after running `python -m olive.workflows.run --config whisper_cpu_int8.json --setup` to optimize the model I only get empty folders.

**Comment by jambayk** [comment]
The local path needs to be for the model directory saved with `save_pretrained`. So, it should be the same as `model` in your example above. 

You also need to save the processor in the same directory. 
```
from transformers import AutoProcessor

# original model 
original_model_name = "openai/whisper-medium"

# load processor
processor = AutoProcessor.from_pretrained(original_model_name)

# path to save the fine-tuned model in transformers pre-trained model format
model_path = "model"

# save process
processor.save_pretrained(model_path)
```

After that you can run the prepare script 

`python prepare_whisper_configs.py --model_name model`

**Comment by jambayk** [comment]
Looks like you are using olive installed from PyPI using `pip install olive-ai` but that release is not in sync with main. 

To use the latest version of Olive, please install it from source using:
`python -m pip install pip install git+https://github.com/microsoft/Olive`
or run
`python -m pip install .` at the root of the Olive directory.

**Comment by marouanetalaa** [comment]
That seems to have been the problem, thank you.
