### ISSUE TITLE
Support for Python 3.9

### ISSUE THREAD

**Issue by antoncyrol** [microsoft/OLive#66]
Are there technical reasons for not support Python 3.9 or are just the wheels missing?

**Comment by leqiao-1** [comment]
OLive is a pure Python package. So there isn't any issue to build OLive package for python 3.9. However, to use OLive inference optimization service, user also needs to install onnxruntime with all EPs and mlperf_loadgen. These two packages only support Python from 3.6 to 3.8. We are working to support Python 3.9 from onnxruntime 1.10 update.

**Comment by leqiao-1** [comment]
Close this issue. Free to reopen for any issue.
