### ISSUE TITLE
[FR]: Hope Olive supports Pydantic version 2.0 or higher

### ISSUE THREAD

**Issue by tangcan1600** [microsoft/Olive#709]
### Proposal Summary

gradio 4.1.2 requires pydantic>=2.0, but you have pydantic 2.0a1 which is incompatible.
olive-ai 0.3.3 requires pydantic<2.0.0, but you have pydantic 2.0a1 which is incompatible.

gradio4.1.2 is not compatible with Pydantic 2.0 or earlier versions，hope olive can support Pydantic version 2.0 or higher，thanks

### What component(s) does this request affect?

- [ ] OliveModels
- [ ] OliveSystems
- [ ] OliveEvaluator
- [ ] Metrics
- [ ] Engine
- [ ] Passes
- [X] Other

**Comment by guotuofeng** [comment]
@tangcan1600, could you clarify the scenario that need gradio 4.1.2? Is it possible that downgrade it to 3.x to unblock you?

**Comment by tangcan1600** [comment]
> @tangcan1600, could you clarify the scenario that need gradio 4.1.2? Is it possible that downgrade it to 3.x to unblock you?

 I want to use the new  features in gradio 4.0, such as ChatInterface

**Comment by tangcan1600** [comment]
I want to use the new features in gradio 4.0, such as ChatInterface

**Comment by tangcan1600** [comment]
I want to use the new features in gradio 4.0, such as ChatInterface

**Comment by tangcan1600** [comment]
> @tangcan1600, could you clarify the scenario that need gradio 4.1.2? Is it possible that downgrade it to 3.x to unblock you?
I want to use the new features in gradio 4.0, such as ChatInterface

**Comment by guotuofeng** [comment]
there is not plan to upgrade to Pydantic 2 in the short term.

**Comment by JKinx** [comment]
@tangcan1600 Olive is now compatible with pydantic v2. 

However, the version `2.0a1` you have in your environment is a pre-release and is missing the module we require to support v2. If you would like to use olive with pydantic v2, please update pydantic to a newer version and install olive from source:
```bash
pip install ---upgrade pydantic
pip install git+https://github.com/microsoft/Olive
```

**Comment by jambayk** [comment]
@tangcan1600 Olive is now compatible with pydantic v2. 

However, the version `2.0a1` you have in your environment is a pre-release and is missing the module we require to support v2. If you would like to use olive with pydantic v2, please update pydantic to a newer version and install olive from source:
```bash
pip install --upgrade pydantic
pip install git+https://github.com/microsoft/Olive
```
