### ISSUE TITLE
[Bug]: Error Node (BeamSearch_node) has input size 12 not in range [min=5, max=10]

### ISSUE THREAD

**Issue by DimQ1** [microsoft/Olive#734]
### What happened?

I try to run example https://github.com/onnxruntime/Whisper-HybridLoop-Onnx-Demo

I followed the instructions and converted the Whisper model.

Run example and get the following error:

Microsoft.ML.OnnxRuntime.OnnxRuntimeException: "[ErrorCode:InvalidGraph] Load model from E:\Work\Dimq1\source\OpenAI\Whisper-HybridLoop-Onnx-Demo\AudioNoteTranscription\bin\Debug\net8.0-windows7.0\Onnx\model.onnx failed:This is an invalid model. In Node, ("BeamSearch_node", BeamSearch, "com.microsoft", -1) : ("log_mel": tensor(float),"max_length": tensor(int32),"min_length": tensor(int32),"num_beams": tensor(int32),"num_return_sequences": tensor(int32),"length_penalty": tensor(float),"repetition_penalty": tensor(float),"","","","","",) -> ("sequences",) , Error Node (BeamSearch_node) has input size 12 not in range [min=5, max=10]."

At the same time onnx model which I get as a resul work fine with python.

### Version?

https://github.com/microsoft/Olive/releases/tag/v0.4.0

**Comment by jambayk** [comment]
Please use the same version of onnxruntime in your application as the one you used to generate the model in Olive.
https://github.com/microsoft/Olive/tree/main/examples/whisper#faq

**Comment by ningpengtao-coder** [comment]
onnxruntime>=1.16.0

**Comment by jambayk** [comment]
What is the version of onnxruntime in the application that is using it? That should also have the same version as the one in your python environment.

**Comment by DimQ1** [comment]
Thanks it helps me ☺
