### ISSUE TITLE
Whisper prompting support

### ISSUE THREAD

**Issue by cfasana** [microsoft/Olive#753]
Using a prompt, the OpenAI Whisper models can be conditioned on the text that appeared in the previous ~30 seconds of audio. One of the possible applications of Whisper prompting is to inform the model to become more likely to output certain jargon that may be use-case specific. As so, this feature can be very helpful.

- Is there a way to support prompts in the Whisper models optimized using Olive? This feature is already supported in HuggingFace Transformers (https://github.com/huggingface/transformers/issues/22395).- 

The following are some useful links concerning Whisper prompting:

- https://platform.openai.com/docs/guides/speech-to-text
- https://github.com/openai/whisper/discussions/963
- https://github.com/openai/whisper/discussions/117

**Comment by jambayk** [comment]
@cfasana thank you for bringing this up and for your experiment with the existing model. 

I also spent some time looking how the changes the transformers library made to add this feature but didn't get around to trying it with our model. 
The beam search op is created and maintained by a separate team from onnxruntime https://github.com/microsoft/onnxruntime/tree/main so we have to talk with the developers about this feature request and see if it can be added. We will keep you posted after discussing this with them.

**Comment by cfasana** [comment]
@jambayk thank you for your feedback.
I had the possibility to do a couple more experiments and noticed that if the prompt is too long (_i.e._, the prompt tokens are too many), then an error is raised stating that the input exceeds _max_length_ (200).
I think that this can be related to what I stated before concerning the maximum number of new tokens.

Do you know whether, at the moment, it is possible to modify the max_length parameter? Right now it seems to be set when loading the model configuration from HuggingFace.

I'll wait for any update.

**Comment by jambayk** [comment]
`max_length` is an input to the model so you can control it yourself. In out example, it is set to `200` here https://github.com/microsoft/Olive/blob/main/examples/whisper/code/whisper_dataset.py#L48.

**Comment by cfasana** [comment]
> @cfasana thank you for bringing this up and for your experiment with the existing model.
> 
> I also spent some time looking how the changes the transformers library made to add this feature but didn't get around to trying it with our model. The beam search op is created and maintained by a separate team from onnxruntime https://github.com/microsoft/onnxruntime/tree/main so we have to talk with the developers about this feature request and see if it can be added. We will keep you posted after discussing this with them.

@jambayk any news on that?

**Comment by jambayk** [comment]
Hi @cfasana, sorry for the delayed response. I talked with the developers of the beam search operator and they told me the limit of 448 tokens is limited by the model so the prompt will always count towards it. 

As it stands, concatenating the prompt and the normal start ids is the way to go.

**Comment by cfasana** [comment]
> Hi @cfasana, sorry for the delayed response. I talked with the developers of the beam search operator and they told me the limit of 448 tokens is limited by the model so the prompt will always count towards it.
> 
> As it stands, concatenating the prompt and the normal start ids is the way to go.

@jambayk  Thanks for the feedback. I ran several experiments with this approach in the past months and it works pretty well. I am happy to now have a double-check on the fact that the approach I used was the correct one.

**Comment by cfasana** [comment]
> Hi @cfasana, sorry for the delayed response. I talked with the developers of the beam search operator and they told me the limit of 448 tokens is limited by the model so the prompt will always count towards it.
> 
> As it stands, concatenating the prompt and the normal start ids is the way to go.

@jambayk  Thanks for the feedback. I ran several experiments with this approach in the past months and it works pretty well. I am happy to now have a double-check on the fact that the approach I used was the correct one.

Thanks, I will close the issue.
