### ISSUE TITLE
[Bug]: Black images generated with SDXL olive model when using Image-to-Image. Text to Image works fine!

### ISSUE THREAD

**Issue by AshD** [microsoft/Olive#764]
### What happened?

Image to Image generates black images with Olive converted SDXL model. Text to Image works fine!
Code below....

Thanks,
Ash

```
import onnxruntime
from optimum.onnxruntime import ORTStableDiffusionXLPipeline,ORTStableDiffusionXLImg2ImgPipeline
from PIL import Image  
from diffusers.utils import load_image

batch_size = 1
image_size = 1024

sess_options = onnxruntime.SessionOptions()
sess_options.add_free_dimension_override_by_name("unet_sample_batch", batch_size * 2)
sess_options.add_free_dimension_override_by_name("unet_sample_channels", 4)
sess_options.add_free_dimension_override_by_name("unet_sample_height", image_size // 8)
sess_options.add_free_dimension_override_by_name("unet_sample_width", image_size // 8)
sess_options.add_free_dimension_override_by_name("unet_time_batch", 1)
sess_options.add_free_dimension_override_by_name("unet_hidden_batch", batch_size * 2)
sess_options.add_free_dimension_override_by_name("unet_hidden_sequence", 77)
sess_options.add_free_dimension_override_by_name("unet_text_embeds_batch", batch_size * 2)
sess_options.add_free_dimension_override_by_name("unet_text_embeds_size", 1280)
sess_options.add_free_dimension_override_by_name("unet_time_ids_batch", batch_size * 2)
sess_options.add_free_dimension_override_by_name("unet_time_ids_size", 6)

model_id="softwareweaver/stable-diffusion-xl-base-1.0-Olive-Onnx"
pipeline = ORTStableDiffusionXLImg2ImgPipeline.from_pretrained(model_id, provider="DmlExecutionProvider", session_options=sess_options)
#url is "https://huggingface.co/datasets/optimum/documentation-images/resolve/main/intel/openvino/sd_xl/castle_friedrich.png"
url = "castle_friedrich.png" #image upscaled to 1024x1024
image = load_image(url)
prompt = "medieval castle by Caspar David Friedrich"

default_config = {
    "sample_size": image_size // 8,
}
pipeline.unet.config = default_config

image = pipeline(prompt, image=image).images[0]
image.save("test.png") # Image created is all black
```

### Version?

olive-ai               0.5.0
omegaconf              2.3.0
onnx                   1.15.0
onnxruntime-directml   1.16.2
onnxruntime-extensions 0.9.0
opencv-python          4.8.1.78
optimum                1.14.1
Pillow                 9.3.0

**Comment by AshD** [comment]
Any idea whether this is a Optimum issue or a data issue with the optimized model?
Text to Image works correctly.

The OnnxStack project which is using this model was having an issue with this model when running the VAEDecoder.
https://github.com/saddam213/OnnxStack/discussions/52

Regards,
Ash

**Comment by jambayk** [comment]
It looks like the vae-decoder is numerically unstable with fp16 in some cases. (https://github.com/microsoft/Olive/pull/635, https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/transformers/models/stable_diffusion/optimize_pipeline.py#L149) 

Can you rerun with `float16` turned off for the vae-decoder? You can set it to `false` here https://github.com/microsoft/Olive/blob/main/examples/directml/stable_diffusion_xl/config_vae_decoder.json#L56

**Comment by jambayk** [comment]
Just checked the latest commit in your hf model. You accidentally updated the encoder with the new decoder model. So, it is using the decoder model (input is `latent_sample`) instead encoder model (input is `sample`) for the encoder in the pipeline.

**Comment by jambayk** [comment]
@PatriceVignola @zhangxiang1993 are either of you familiar with this issue? Thanks!

**Comment by PatriceVignola** [comment]
@AshD We had a similar issue before and had to keep both the VAE encoder and VAE decoder in fp32 to make it work. It was supposed to be fixed with the latest version though. Can you try keeping both in fp32?

**Comment by AshD** [comment]
Thanks @PatriceVignola 

I experimented with it. 
Keeping both as FP32 works :-)
Keeping Decoder FP32 only, does **not** work 
**Keeping Encoder FP32 only works :-)**

I think it makes sense to keep the Encoder only to FP32 and let the decoder FP16 to save time and space.

Will do more testing and keep you updated.

Thanks,
Ash

**Comment by PatriceVignola** [comment]
Thanks for trying it out! It makes sense, we already did the work to target the exact nodes that were causing the black output for the decoder, so it sounds like we need to do the same thing for the encoder:

https://github.com/microsoft/Olive/blob/c29b87c3f872c9f88e1c96119635f2765a5c406c/examples/directml/stable_diffusion_xl/config_vae_decoder.json#L81

**Comment by AshD** [comment]
Happy to test this out when it is checked in :-)
