### ISSUE TITLE
Olive requires an old version of torchmetrics ~= 0.10.0

### ISSUE THREAD

**Issue by nicolas-mng** [microsoft/Olive#768]
### Proposal Summary

Hello,
Thanks for your great work!

The latest torchmetrics version is 1.2.0. Imposing a version < 1 seems to be a bit limiting, especially when working with latest versions of ``lightning``. What is blocking the update of the requirement?

Best,
Nico

### What component(s) does this request affect?

- [ ] OliveModels
- [ ] OliveSystems
- [ ] OliveEvaluator
- [ ] Metrics
- [ ] Engine
- [ ] Passes
- [X] Other

**Comment by trajepl** [comment]
Thanks for you suggestion! https://github.com/microsoft/Olive/pull/773 The pr is merged, feel free to have a try.

**Comment by nicolas-mng** [comment]
Sweet, this was fast! Thanks
