### ISSUE TITLE
[Bug]: assert conversion_footprint and optimizer_footprint for LCM SDXL model

### ISSUE THREAD

**Issue by AshD** [microsoft/Olive#772]
### What happened?

I am trying to convert https://huggingface.co/latent-consistency/lcm-sdxl 

I modified the line 262 in file stable_diffusion_xl.py (**pipeline = DiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float32**)

to the following lines to load the LCM pipeline correctly
```
    unet = UNet2DConditionModel.from_pretrained("latent-consistency/lcm-sdxl", torch_dtype=torch.float32)
    pipeline = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", unet=unet, torch_dtype=torch.float32)
    pipeline.scheduler = LCMScheduler.from_config(pipeline.scheduler.config)
```

And here is the output...

```
python stable_diffusion_xl_lcm.py --model_id=latent-consistency/lcm-sdxl --optimize
WARNING: latent-consistency/lcm-sdxl is not an officially supported model for this example and may not work as expected.
Download stable diffusion PyTorch pipeline...
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 7/7 [00:00<00:00, 17.84it/s]
The config attributes {'skip_prk_steps': True} were passed to LCMScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.

Optimizing vae_encoder
[2023-12-03 19:55:19,846] [INFO] [engine.py:181:setup_accelerators] Running workflow on accelerator specs: gpu-dml
[2023-12-03 19:55:19,857] [INFO] [engine.py:931:_run_pass] Running pass convert:OnnxConversion
[2023-12-03 19:55:19,858] [WARNING] [engine.py:914:_run_passes] Skipping evaluation as model was pruned
[2023-12-03 19:55:19,858] [INFO] [engine.py:612:create_pareto_frontier_footprints] Output all 0 models
[2023-12-03 19:55:19,859] [INFO] [engine.py:359:run] Run history for gpu-dml:
[2023-12-03 19:55:19,861] [INFO] [engine.py:636:dump_run_history] run history:
+--------------------------------------------------------------------------------------+----------------------------------+----------------+----------------+-----------+
| model_id                                                                             | parent_model_id
  | from_pass      |   duration_sec | metrics   |
+======================================================================================+==================================+================+================+===========+
| 37fad7b0de93edb1a09b5cc85cca78ab                                                     |
  |                |                |           |
+--------------------------------------------------------------------------------------+----------------------------------+----------------+----------------+-----------+
| 120_OnnxConversion-37fad7b0de93edb1a09b5cc85cca78ab-16f2a37f9cd543024ce55445ffe26e2b | 37fad7b0de93edb1a09b5cc85cca78ab | OnnxConversion |       0.135593 |           |
+--------------------------------------------------------------------------------------+----------------------------------+----------------+----------------+-----------+
[2023-12-03 19:55:19,877] [INFO] [engine.py:374:run] No packaging config provided, skip packaging artifacts
Traceback (most recent call last):
  File "C:\AI\research\olive\olive\examples\directml\stable_diffusion_xl\stable_diffusion_xl_lcm.py", line 480, in <module>
    optimize(args.model_id, is_refiner_model, unoptimized_model_dir, optimized_model_dir)
  File "C:\AI\research\olive\olive\examples\directml\stable_diffusion_xl\stable_diffusion_xl_lcm.py", line 302, in optimize
    assert conversion_footprint and optimizer_footprint
AssertionError

```

Thanks,
Ash

### Version?

Latest Master branch

olive-ai               0.5.0
omegaconf              2.3.0
onnx                   1.15.0
onnxruntime-directml   1.16.2
onnxruntime-extensions 0.9.0
opencv-python          4.8.1.78
optimum                1.14.1

**Comment by trajepl** [comment]
It is great. Thanks for trying Olive. Would you mind to attach the Olive link to the model page you shared? It might be helpful to guide customers to Olive which can provides more potential for Olive optimization. :)

Olive link: https://github.com/microsoft/Olive
Olive stable diffusion link: https://github.com/microsoft/Olive/tree/main/examples/directml/stable_diffusion_xl

**Comment by AshD** [comment]
Will do

**Comment by louwangzhiyuY** [comment]
> Thanks @trajepl
> 
> The cache was the issue.
> 
> Model is uploaded here https://huggingface.co/softwareweaver/Latent-Consistency-xl-Olive-Onnx
> 
> Regards, Ash

how to fix?  I meet silimar issue when run llama_v2

**Comment by trajepl** [comment]
> Also, seems your local cache is accumulated too much. (the id of conversion is `120`). Please try to clean cache before the run. For SD case, the cache folder should be `cache`. ![image](https://private-user-images.githubusercontent.com/13343117/287643480-f4657a96-94ed-4c98-92e4-e334873ab806.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODMyNjYsIm5iZiI6MTcwMjk4Mjk2NiwicGF0aCI6Ii8xMzM0MzExNy8yODc2NDM0ODAtZjQ2NTdhOTYtOTRlZC00Yzk4LTkyZTQtZTMzNDg3M2FiODA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDEwNDkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyYzMxNzJmYjkxZTNmNmI3MGQ3YjMwZjNmZTUwZjlmOTZhM2ZhYWFmZjhmZjVkZmE4ZDdjMDc4Y2E0ZDZkM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K1INQ6N2RCkCyESHWru87e6ZomNM2oPO4VkQzaVzuM8)

@louwangzhiyuY check this.

**Comment by KarpovVolodymyr** [comment]
@louwangzhiyuY Hi. Have you found out how to fix it? I also have the same problem when run llama-2

**Comment by trajepl** [comment]
> @louwangzhiyuY Hi. Have you found out how to fix it? I also have the same problem when run llama-2

Remove local cache manually. Or set `clean_cache` as `True`
![image](https://github.com/microsoft/Olive/assets/13343117/57981385-ec7b-41e3-89ed-65d13721bdf3)

**Comment by OZoneRidah** [comment]
> > @louwangzhiyuY Hi. Have you found out how to fix it? I also have the same problem when run llama-2
> 
> Remove local cache manually. Or set `clean_cache` as `True` ![image](https://private-user-images.githubusercontent.com/13343117/300321633-57981385-ec7b-41e3-89ed-65d13721bdf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxOTA3NjksIm5iZiI6MTcwNzE5MDQ2OSwicGF0aCI6Ii8xMzM0MzExNy8zMDAzMjE2MzMtNTc5ODEzODUtZWM3Yi00MWUzLTg5ZWQtNjVkMTM3MjFiZGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDAzMzQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMDEzNzcxMjFjOTI3NTUxMjEzNDYwMDJjNWM5ZDJmZjIwMDE1YjZlODdhZThiYzYxZDcwYzJhNjUxOTIwZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.duodD9lBv6GA2bqIknxiYJ-D9o7bEx6KnDxar8o6LgI)

Hey, where would I be able to find this file to change the local cache to true. Im looking all over into my stable-diffusion-webui-directml.

**Comment by trajepl** [comment]
Take this as an example, you need to update all the json file to enable `clean_cache`.
![image](https://github.com/microsoft/Olive/assets/13343117/2d9dd694-cc1c-4edb-a8ac-d59cef037faf)

**Comment by OZoneRidah** [comment]
> Take this as an example, you need to update all the json file to enable `clean_cache`. ![image](https://private-user-images.githubusercontent.com/13343117/302498129-2d9dd694-cc1c-4edb-a8ac-d59cef037faf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxOTI1MzUsIm5iZiI6MTcwNzE5MjIzNSwicGF0aCI6Ii8xMzM0MzExNy8zMDI0OTgxMjktMmQ5ZGQ2OTQtY2MxYy00ZWRiLWE4YWMtZDU5Y2VmMDM3ZmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDA0MDM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxM2NhMzFhODdjMDRmNGJmYjA2M2JmY2NmYWFlNWI3NTM0N2M1YjE1NDhlYmRmNWU2MmQ0NWQzN2M3YjdmNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tfTOmPbM3Gu8dXKR6nJcihOlQ_z1vtL50Vn4xGSgzfA)

looks like im looking at a different one, for me my issue is with stable diffusion v1.5, but also getting the exact same error the previous user posted. 
![image](https://github.com/microsoft/Olive/assets/159099490/dd8e90c7-978d-4384-b653-015c7c42844f)
![image](https://github.com/microsoft/Olive/assets/159099490/be8bc88b-4f21-49d4-90a9-1aab5f65f228)

**Comment by louwangzhiyuY** [comment]
> @louwangzhiyuY Hi. Have you found out how to fix it? I also have the same problem when run llama-2

No, still have fail.
