### ISSUE TITLE
How do I create a SDXL Olive model that is optimized for various Execution providers - DirectML, CPU, GPU

### ISSUE THREAD

**Issue by AshD** [microsoft/Olive#776]
### What happened?

This might be more of a documentation issue...

I loaded my optimized model with 
```
pipeline = ORTStableDiffusionXLPipeline.from_pretrained(model_id, provider="CPUExecutionProvider", session_options=sess_options)

  File "C:\AI\research\olive\.venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for GroupNorm(1) node with name 'GroupNorm_22'
```

The same model **works** with the DmlExecutionProvider fine.

I generated this model by modifying the sub-model config files to add the cpu and CPUExecutionProvider to the accelerators and execution_providers and running python stable_diffusion_xl.py --model_id=stabilityai/stable-diffusion-xl-base-1.0 --optimize

```
"systems": {
        "local_system": {
            "type": "LocalSystem",
            "config": {
                "accelerators": ["gpu","cpu"]
            }
        }
    },

 "engine": {
        "search_strategy": {
            "execution_order": "joint",
            "search_algorithm": "exhaustive"
        },
        "evaluator": "common_evaluator",
        "evaluate_input_model": false,
        "host": "local_system",
        "target": "local_system",
        "cache_dir": "cache",
        "output_name": "text_encoder",
        "output_dir": "footprints",
        "execution_providers": ["DmlExecutionProvider","CPUExecutionProvider"]
    }
```

Is other config changes, I need to do to support both the DirectML and CPU execution providers? 

Thanks,
Ash

### Version?

Latest Master branch - olive-ai               0.5.0

**Comment by jambayk** [comment]
Some of the fusion options are not compatible with CPU or CUDA eps. For example, GroupNorm is not available on CPU. 

I am currently working on adding cuda options to the models but it's not ready yet https://github.com/microsoft/Olive/tree/jambayk/sd-cuda

**Comment by jambayk** [comment]
Yes, because of the EP/target specific fusion options, creating different models would be best. However, I am not familiar if any work has been done to optimize models for OpenVino EP yet or if the CPU EP model works well for that EP.

**Comment by jambayk** [comment]
@AshD fyi, the cuda option PR has been merged https://github.com/microsoft/Olive/pull/778. 
You will still need to set the encoder's `float16` to `false` if you want to use the sdxl base model for img2img.

**Comment by AshD** [comment]
Thanks @jambayk 

Any idea if CUDA model is faster than DirectML one?

One of the use cases for our Windows app (FusionQuill.AI) is lot of new computers (esp. laptops don't have a GPU) and some form of CPU accelerated model is going to be required for AI. Would love see the Olive or OnnxRuntime team tackle this use case in the future.

Regards,
Ash

**Comment by jambayk** [comment]
I don't have a DirectML compatible windows machine, so I haven't benchmarked and compared the two. 

For these models, the current focus has been on directml, cuda and tensorrt. I will update here if we add options for cpu or openvino optimization.

**Comment by AshD** [comment]
Thanks @jambayk

Will try to benchmark and check it out.
