### ISSUE TITLE
No safety checker in SDXL

### ISSUE THREAD

**Issue by natke** [microsoft/Olive#804]
The stable diffusion XL examples depicts and describes a safety model but IIUC there is no safety model in this pipeline

**Comment by jambayk** [comment]
@PatriceVignola The pipeline image and memory requirement estimates in the SDXL readme were directly copied over from the SD readme. Should we update those numbers to avoid confusions?

**Comment by jambayk** [comment]
I can edit the image (unless you have access to the original source of the image, I think Justin created it?)

But I don't have the estimates for the memory requirement.
