### ISSUE TITLE
[Bug]: Merged ONNX model exceeds 2GB, the model will not be checked without `save_path` given.

### ISSUE THREAD

**Issue by louwangzhiyuY** [microsoft/Olive#831]
### What happened?

Running pass merge:OptimumMerging
Merged ONNX model exceeds 2GB, the model will not be checked without `save_path` given.

the error will cause model corrupt. 

7 : INVALID_PROTOBUF : Load model from cache\models\3_OptimumMerging-2-29928aa56000b48c6135423fa1102e45-gpu-dml\output_model\decoder_model_merged.onnx failed:Protobuf parsing failed.

full fail log:

(olive-venv) C:\work\AI\directml\Olive\examples\directml\llama_v2>python llama_v2.py --model_type=7b-chat

Optimizing argmax_sampling
[2023-12-18 19:02:56,888] [INFO] [engine.py:181:setup_accelerators] Running workflow on accelerator specs: gpu-dml
[2023-12-18 19:02:56,904] [INFO] [engine.py:931:_run_pass] Running pass convert:OnnxConversion
[2023-12-18 19:02:57,217] [INFO] [footprint.py:183:create_pareto_frontier] pareto frontier points: 0_OnnxConversion-14dc7b7c3125d3ad1222f0b9e2e5b807-0f2f01796d1fdfcd7c7058df3febec4e
{
  "latency-avg": 0.21688
}
[2023-12-18 19:02:57,217] [INFO] [engine.py:612:create_pareto_frontier_footprints] Output all 1 models
[2023-12-18 19:02:57,217] [INFO] [engine.py:359:run] Run history for gpu-dml:
[2023-12-18 19:02:57,217] [INFO] [engine.py:636:dump_run_history] run history:
+------------------------------------------------------------------------------------+----------------------------------+----------------+----------------+--------------------------+
| model_id                                                                           | parent_model_id
| from_pass      |   duration_sec | metrics                  |
+====================================================================================+==================================+================+================+==========================+
| 14dc7b7c3125d3ad1222f0b9e2e5b807                                                   |
|                |                |                          |
+------------------------------------------------------------------------------------+----------------------------------+----------------+----------------+--------------------------+
| 0_OnnxConversion-14dc7b7c3125d3ad1222f0b9e2e5b807-0f2f01796d1fdfcd7c7058df3febec4e | 14dc7b7c3125d3ad1222f0b9e2e5b807 | OnnxConversion |        0.17158 | {                        |
|                                                                                    |
|                |                |   "latency-avg": 0.21688 |
|                                                                                    |
|                |                | }                        |
+------------------------------------------------------------------------------------+----------------------------------+----------------+----------------+--------------------------+
[2023-12-18 19:02:57,217] [INFO] [engine.py:374:run] No packaging config provided, skip packaging artifacts
Optimized Model   : C:\work\AI\directml\Olive\examples\directml\llama_v2\cache\models\0_OnnxConversion-14dc7b7c3125d3ad1222f0b9e2e5b807-0f2f01796d1fdfcd7c7058df3febec4e\output_model\model.onnx

Optimizing llama_v2
[2023-12-18 19:02:57,240] [INFO] [engine.py:181:setup_accelerators] Running workflow on accelerator specs: gpu-dml
[2023-12-18 19:02:57,275] [INFO] [engine.py:931:_run_pass] Running pass convert:OnnxConversion
C:\work\AI\directml\Olive\olive-venv\Lib\site-packages\torch\onnx\_internal\jit_utils.py:307: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ..\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
C:\work\AI\directml\Olive\olive-venv\Lib\site-packages\torch\onnx\utils.py:702: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ..\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
  _C._jit_pass_onnx_graph_shape_type_inference(
C:\work\AI\directml\Olive\olive-venv\Lib\site-packages\torch\onnx\utils.py:1209: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at ..\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
  _C._jit_pass_onnx_graph_shape_type_inference(
[2023-12-18 19:30:14,982] [INFO] [engine.py:931:_run_pass] Running pass optimize:OrtTransformersOptimization
[2023-12-18 19:47:06,898] [INFO] [engine.py:931:_run_pass] Running pass merge:OptimumMerging
_Merged ONNX model exceeds 2GB, the model will not be checked without `save_path` given.
[2023-12-18 19:50:10,438] [ERROR] [engine.py:1004:_run_pass] Pass run failed._
Traceback (most recent call last):
  File "C:\work\AI\directml\Olive\olive\engine\engine.py", line 992, in _run_pass
    output_model_config = host.run_pass(p, input_model_config, data_root, output_model_path, pass_search_point)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\AI\directml\Olive\olive\systems\local.py", line 34, in run_pass
    output_model = the_pass.run(model, data_root, output_model_path, point)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\AI\directml\Olive\olive\passes\olive_pass.py", line 373, in run
    output_model = self._run_for_config(model, data_root, config, output_model_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\AI\directml\Olive\olive\passes\onnx\optimum_merging.py", line 84, in _run_for_config
    onnxruntime.InferenceSession(output_model_path, sess_options, providers=[execution_provider])
  File "C:\work\AI\directml\Olive\olive-venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\work\AI\directml\Olive\olive-venv\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 452, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from cache\models\3_OptimumMerging-2-29928aa56000b48c6135423fa1102e45-gpu-dml\output_model\decoder_model_merged.onnx failed:Protobuf parsing failed.
[2023-12-18 19:50:10,890] [WARNING] [engine.py:914:_run_passes] Skipping evaluation as model was pruned
[2023-12-18 19:50:10,903] [INFO] [engine.py:612:create_pareto_frontier_footprints] Output all 0 models
[2023-12-18 19:50:10,906] [INFO] [engine.py:359:run] Run history for gpu-dml:
[2023-12-18 19:50:10,915] [INFO] [engine.py:636:dump_run_history] run history:
+------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+-----------------------------+----------------+-----------+
| model_id                                                                           | parent_model_id
                                                  | from_pass                   |   duration_sec | metrics   |
+====================================================================================+====================================================================================+=============================+================+===========+
| 714a6e03d859d8c760fef044a870005b                                                   |
                                                  |                             |                |           |
+------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+-----------------------------+----------------+-----------+
| 1_OnnxConversion-714a6e03d859d8c760fef044a870005b-0f2f01796d1fdfcd7c7058df3febec4e | 714a6e03d859d8c760fef044a870005b                                                   | OnnxConversion              |       1637.68  |           |
+------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+-----------------------------+----------------+-----------+
| 2_OrtTransformersOptimization-1-46d47fd3ba3201590094426782e1d9f2                   | 1_OnnxConversion-714a6e03d859d8c760fef044a870005b-0f2f01796d1fdfcd7c7058df3febec4e | OrtTransformersOptimization |       1011.85  |           |
+------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+-----------------------------+----------------+-----------+
| 3_OptimumMerging-2-29928aa56000b48c6135423fa1102e45-gpu-dml                        | 2_OrtTransformersOptimization-1-46d47fd3ba3201590094426782e1d9f2                   | OptimumMerging              |        183.946 |           |
+------------------------------------------------------------------------------------+------------------------------------------------------------------------------------+-----------------------------+----------------+-----------+
[2023-12-18 19:50:10,917] [INFO] [engine.py:374:run] No packaging config provided, skip packaging artifacts
Traceback (most recent call last):
  File "C:\work\AI\directml\Olive\examples\directml\llama_v2\llama_v2.py", line 214, in <module>
    optimize(optimized_model_dir, args.model_type)
  File "C:\work\AI\directml\Olive\examples\directml\llama_v2\llama_v2.py", line 92, in optimize
    optimized_olive_model = ONNXModelHandler(**merging_footprint["model_config"]["config"])
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'config'

### Version?

onnx                      1.15.0
onnxruntime               1.16.3
onnxruntime-directml      1.16.3
optimum                   1.17.0.dev0

**Comment by AjithPrabhakaran** [comment]
Do we have any solution for this issue. Am also facing the error. Can someone help.

**Comment by guotuofeng** [comment]
what's the error if the save_path is given?

**Comment by louwangzhiyuY** [comment]
> Do we have any solution for this issue. Am also facing the error. Can someone help.

Not solve yet

**Comment by louwangzhiyuY** [comment]
> what's the error if the save_path is given?

No help.

**Comment by Yajun-Yang** [comment]
add two paramters in config file can solve the issue.

                "save_as_external_data": true,
                "all_tensors_to_one_file": true
