### ISSUE TITLE
[Bug]: stable diffusion performance degrade

### ISSUE THREAD

**Issue by Jay19751103** [microsoft/Olive#834]
### What happened?

git clone olive with conda python 3.11 env
cd olive
pip install .
cd example\directml\stable-diffusion
do optimize with --clean_cache

### Version?
Device 4060M

d29ac9006365a12c8f6e8fb9150aca9786897190 issue occurred. 1.8 it/s
before is okay 4.7 it/s

**Comment by jambayk** [comment]
It is probably because the image during generation changed from `512` to `768` in that PR.

Can you try running the inference test using `python stable_diffusion.py --image_size 512`?

**Comment by Jay19751103** [comment]
Thank you. set size 512 will be fine.
