### ISSUE TITLE
ImportError: cannot import name 'load_model' from 'onnxruntime.quantization.quant_utils'

### ISSUE THREAD

**Issue by lonestarfire** [microsoft/Olive#849]
I went and installed the Olive directml. I was following the steps in readme. When I got the command to run python stable_diffusion.py --optimize located in C:\Windows\System32\olive\examples\directml\stable_diffusion>

I got the error in the subject. Below is the entire output from the command. 

(olive) C:\Windows\System32\olive\examples\directml\stable_diffusion>python stable_diffusion.py --provider cuda --optimize
Traceback (most recent call last):
  File "C:\Windows\System32\olive\examples\directml\stable_diffusion\stable_diffusion.py", line 18, in <module>
    from olive.workflows import run as olive_run
  File "C:\Users\tommy\miniconda3\envs\olive\lib\site-packages\olive\workflows\__init__.py", line 5, in <module>
    from olive.workflows.run.run import run
  File "C:\Users\tommy\miniconda3\envs\olive\lib\site-packages\olive\workflows\run\run.py", line 16, in <module>
    from olive.passes import Pass
  File "C:\Users\tommy\miniconda3\envs\olive\lib\site-packages\olive\passes\__init__.py", line 6, in <module>
    from olive.passes.onnx import *  # noqa: F403
  File "C:\Users\tommy\miniconda3\envs\olive\lib\site-packages\olive\passes\onnx\__init__.py", line 17, in <module>
    from olive.passes.onnx.vitis_ai_quantization import VitisAIQuantization
  File "C:\Users\tommy\miniconda3\envs\olive\lib\site-packages\olive\passes\onnx\vitis_ai_quantization.py", line 18, in <module>
    from olive.passes.onnx.vitis_ai import quantize_static
  File "C:\Users\tommy\miniconda3\envs\olive\lib\site-packages\olive\passes\onnx\vitis_ai\__init__.py", line 10, in <module>
    from olive.passes.onnx.vitis_ai.quantize import quantize_static
  File "C:\Users\tommy\miniconda3\envs\olive\lib\site-packages\olive\passes\onnx\vitis_ai\quantize.py", line 15, in <module>
    from onnxruntime.quantization.quant_utils import QuantFormat, QuantizationMode, QuantType, load_model
ImportError: cannot import name 'load_model' from 'onnxruntime.quantization.quant_utils' (C:\Users\tommy\miniconda3\envs\olive\lib\site-packages\onnxruntime\quantization\quant_utils.py)

(olive) C:\Windows\System32\olive\examples\directml\stable_diffusion>

I tried running this command without (--Provider cuda) and I got the below result. 

Traceback (most recent call last):
  File "C:\Windows\System32\olive\examples\directml\stable_diffusion\stable_diffusion.py", line 18, in <module>
    from olive.workflows import run as olive_run
  File "C:\Users\tommy\miniconda3\envs\olive\lib\site-packages\olive\workflows\__init__.py", line 5, in <module>
    from olive.workflows.run.run import run
  File "C:\Users\tommy\miniconda3\envs\olive\lib\site-packages\olive\workflows\run\run.py", line 16, in <module>
    from olive.passes import Pass
  File "C:\Users\tommy\miniconda3\envs\olive\lib\site-packages\olive\passes\__init__.py", line 6, in <module>
    from olive.passes.onnx import *  # noqa: F403
  File "C:\Users\tommy\miniconda3\envs\olive\lib\site-packages\olive\passes\onnx\__init__.py", line 17, in <module>
    from olive.passes.onnx.vitis_ai_quantization import VitisAIQuantization
  File "C:\Users\tommy\miniconda3\envs\olive\lib\site-packages\olive\passes\onnx\vitis_ai_quantization.py", line 18, in <module>
    from olive.passes.onnx.vitis_ai import quantize_static
  File "C:\Users\tommy\miniconda3\envs\olive\lib\site-packages\olive\passes\onnx\vitis_ai\__init__.py", line 10, in <module>
    from olive.passes.onnx.vitis_ai.quantize import quantize_static
  File "C:\Users\tommy\miniconda3\envs\olive\lib\site-packages\olive\passes\onnx\vitis_ai\quantize.py", line 15, in <module>
    from onnxruntime.quantization.quant_utils import QuantFormat, QuantizationMode, QuantType, load_model
ImportError: cannot import name 'load_model' from 'onnxruntime.quantization.quant_utils' (C:\Users\tommy\miniconda3\envs\olive\lib\site-packages\onnxruntime\quantization\quant_utils.py)

System is Windows 11 Pro
x64
Processor	AMD Ryzen 9 3950X 16-Core Processor, 3975 Mhz, 16 Core(s), 32 Logical Processor(s)
GPU	AMD Radeon RX 7900 XTX VRAM 24560 MB GDDR6 2500 MHz

16.0 GB RAM

**Comment by guotuofeng** [comment]
It seems you are using Olive 0.2.1? please upgrade to latest version or using main branch directly.

**Comment by lonestarfire** [comment]
after ensuring that I am on the latest version. I went through the steps again and got the following ouput:

(olive) C:\Windows\System32\Olive\examples\directml\stable_diffusion>python stable_diffusion.py --provider cuda --optimize
Traceback (most recent call last):
  File "C:\Windows\System32\Olive\examples\directml\stable_diffusion\stable_diffusion.py", line 22, in <module>
    from olive.model import ONNXModelHandler
ImportError: cannot import name 'ONNXModelHandler' from 'olive.model' (C:\Users\tommy\miniconda3\envs\olive\lib\site-packages\olive\model\__init__.py)


when attempting without the provider cuda argumnet

(olive) C:\Windows\System32\Olive\examples\directml\stable_diffusion>python stable_diffusion.py --optimize
Traceback (most recent call last):
  File "C:\Windows\System32\Olive\examples\directml\stable_diffusion\stable_diffusion.py", line 22, in <module>
    from olive.model import ONNXModelHandler
ImportError: cannot import name 'ONNXModelHandler' from 'olive.model' (C:\Users\tommy\miniconda3\envs\olive\lib\site-packages\olive\model\__init__.py)

**Comment by guotuofeng** [comment]
it seems your olive installation folder is pretty strange. Should not it under site-packages/lib? 

Would you please provide more information on your env?

**Comment by lonestarfire** [comment]
So I tried a few different things. Turns out I missed the command after the git pull to install olive. I ran that command and I also realized that I was uninstalling onnxruntime directml and installing onnxruntime gpu. So I made sure it was installing direcml and I was able to get to the optimization without error. I also changed the optimize command from using cuda to dml this appears to solved the issue

**Comment by liqian29** [comment]
Hi Lonestarfire, I encounter the same error as you, below is the steps I used. could you please help share which command you missed that potetnially fix this error? BTW, I also use AMD Radeon GPU for this deployment.  thanks if you can share the experience. 
BTW, i check the onnixruntime directml already install when pip install -r requirements.txt. should I install onnxruntime gpu?

conda create -n olive-env python=3.10.13
conda activate olive-env
git clone https://github.com/microsoft/Olive.git (use web download and rename folder name to Olive)
cd Olive
(olive-env) C:\Users\sa\Olive>python -m pip install olive-ai[directml]==0.4.0 (install olive success.pic )
(olive-env) C:\Users\sa\Olive\olive>cd examples/directml/stable_diffusion
(olive-env) C:\Users\sa\Olive\olive>pip install -r requirements.txt  (pic)
(olive-env) C:\Users\sa\Olive\examples\directml\stable_diffusion>git clone https://github.com/microsoft/olive --branch v0.4.0
(olive-env) C:\Users\sa\Olive\examples\directml\stable_diffusion>pip install -r requirements.txt

**Comment by liqian29** [comment]
paste the error:
(olive-env) C:\Users\sa\Olive\examples\directml\stable_diffusion>python stable_diffusion.py --optimize
Traceback (most recent call last):
  File "C:\Users\sa\Olive\examples\directml\stable_diffusion\stable_diffusion.py", line 22, in <module>
    from olive.model import ONNXModelHandler
ImportError: cannot import name 'ONNXModelHandler' from 'olive.model' (C:\Users\sa\anaconda3\envs\olive-env\lib\site-packages\olive\model\__init__.py)

**Comment by guotuofeng** [comment]
> ONNXModelHandler

Please use the main branch Olive

**Comment by natsu249** [comment]
i have the same error: from onnxruntime.quantization.quant_utils import QuantFormat, QuantizationMode, QuantType, load_model
ImportError: cannot import name 'load_model' from 'onnxruntime.quantization.quant_utils' (C:\Users\vuurdraak\miniconda3\envs\olive\lib\site-packages\onnxruntime\quantization\quant_utils.py)

i checked if the map and file exist and they do but it does not work

**Comment by natsu249** [comment]
well i checked but i have onnxruntime-1.17.1

**Comment by guotuofeng** [comment]
> well i checked but i have onnxruntime-1.17.1 i wish i just had a NVidia card but when i bought my new gpu the amd ones where cheaper and also kinda better
> 
> i got past it but now i get this. File "C:\Users\user\olive\examples\directml\stable_diffusion\stable_diffusion.py", line 288, in optimize(args.model_id, unoptimized_model_dir, optimized_model_dir) File "C:\Users\user\olive\examples\directml\stable_diffusion\stable_diffusion.py", line 164, in optimize pipeline = StableDiffusionPipeline.from_pretrained(base_model_id, torch_dtype=torch.float32) File "C:\Users\user\miniconda3\envs\olive\lib\site-packages\huggingface_hub\utils_validators.py", line 118, in _inner_fn return fn(*args, **kwargs) File "C:\Users\user\miniconda3\envs\olive\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1105, in from_pretrained if not os.path.isdir(pretrained_model_name_or_path): File "C:\Users\user\miniconda3\envs\olive\lib\genericpath.py", line 42, in isdir st = os.stat(s) TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

What's your olive-ai version, is it 0.2.1?

**Comment by natsu249** [comment]
how do i check
