### ISSUE TITLE
assert conversion_footprint and optimizer_footprint with Stable Diffusion conversion

### ISSUE THREAD

**Issue by AshD** [microsoft/Olive#855]
I am trying to convert https://civitai.com/models/36520/ghostmix

I modified the Stable Diffusion convert to load the file locally

`pipeline = StableDiffusionPipeline.from_single_file("./models/ghostmix_v20Bakedvae.safetensors", torch_dtype=torch.float16).to("cuda")
`

Output

```
python stable_diffusion_local2.py --model_id=softwareweaver/ghostmix --optimize
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: DLL load failed while importing libtriton: The specified module could not be found.
Download stable diffusion PyTorch pipeline...
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["bos_token_id"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["eos_token_id"]` will be overriden.

Optimizing vae_encoder
[2024-01-03 17:11:48,135] [INFO] [engine.py:181:setup_accelerators] Running workflow on accelerator specs: gpu-dml
[2024-01-03 17:11:48,156] [INFO] [engine.py:931:_run_pass] Running pass convert:OnnxConversion
[2024-01-03 17:11:48,159] [WARNING] [engine.py:914:_run_passes] Skipping evaluation as model was pruned
[2024-01-03 17:11:48,159] [INFO] [engine.py:612:create_pareto_frontier_footprints] Output all 0 models
[2024-01-03 17:11:48,160] [INFO] [engine.py:359:run] Run history for gpu-dml:
[2024-01-03 17:11:48,163] [INFO] [engine.py:636:dump_run_history] run history:
+------------------------------------------------------------------------------------+----------------------------------+----------------+----------------+-----------+
| model_id                                                                           | parent_model_id                  | from_pass      |   duration_sec | metrics   |
+====================================================================================+==================================+================+================+===========+
| bd3baafdee1ba8aa8535c88f59954127                                                   |                                  |                |                |           |
+------------------------------------------------------------------------------------+----------------------------------+----------------+----------------+-----------+
| 1_OnnxConversion-bd3baafdee1ba8aa8535c88f59954127-c0506ab83b20c8664e9ca29fd4d895a5 | bd3baafdee1ba8aa8535c88f59954127 | OnnxConversion |       0.101178 |           |
+------------------------------------------------------------------------------------+----------------------------------+----------------+----------------+-----------+
[2024-01-03 17:11:48,164] [INFO] [engine.py:374:run] No packaging config provided, skip packaging artifacts
Traceback (most recent call last):
  File "C:\AI\research\olive\olive\examples\directml\stable_diffusion\stable_diffusion_local2.py", line 456, in <module>
    main()
  File "C:\AI\research\olive\olive\examples\directml\stable_diffusion\stable_diffusion_local2.py", line 433, in main
    optimize(args.model_id, args.provider, unoptimized_model_dir, optimized_model_dir)
  File "C:\AI\research\olive\olive\examples\directml\stable_diffusion\stable_diffusion_local2.py", line 299, in optimize
    assert conversion_footprint and optimizer_footprint
AssertionError
```

I got this error before for SDXL and the cause was the cache. Deleting it cleared it there. But did NOT solve the issue here.

**Olive config**
olive-ai               0.5.0
omegaconf              2.3.0
onnx                   1.15.0
onnxruntime-directml   1.16.3
optimum                1.16.1

**Olive logs**
VAE Encoder footprint.json

`{"bd3baafdee1ba8aa8535c88f59954127": {"parent_model_id": null, "model_id": "bd3baafdee1ba8aa8535c88f59954127", "model_config": null, "from_pass": null, "pass_run_config": null, "is_pareto_frontier": false, "metrics": null, "start_time": 0, "end_time": 0}, "1_OnnxConversion-bd3baafdee1ba8aa8535c88f59954127-c0506ab83b20c8664e9ca29fd4d895a5": {"parent_model_id": "bd3baafdee1ba8aa8535c88f59954127", "model_id": "1_OnnxConversion-bd3baafdee1ba8aa8535c88f59954127-c0506ab83b20c8664e9ca29fd4d895a5", "model_config": {"is_pruned": true}, "from_pass": "OnnxConversion", "pass_run_config": {"script_dir": null, "user_script": null, "target_opset": 14, "use_dynamo_exporter": false, "use_device": null, "torch_dtype": null, "parallel_jobs": null, "merge_components": false, "save_as_external_data": false, "all_tensors_to_one_file": true, "external_data_name": null, "size_threshold": 1024, "convert_attribute": false}, "is_pareto_frontier": false, "metrics": null, "start_time": 1704330673.66373, "end_time": 1704330673.764908}}`

**Other information**
 - OS: Windows 11

**Comment by guotuofeng** [comment]
From the log, it seems you only run OnnxConversion and without OrtTransformersOptimization? please remove the assertion of optimizer_footprint in your local code.

**Comment by AshD** [comment]
Thanks Mike. What do I need to change to get the Optimized model?

I got the current stable diffusion example folder via a git pull yesterday.

**Comment by AshD** [comment]
I commented out the Assertion line but it failed in the next line due to model_config being null for the conversion footprint.

**Comment by guotuofeng** [comment]
> I commented out the Assertion line but it failed in the next line due to model_config being null for the conversion footprint.

What's the conversion errors? are there any output model of conversion?

**Comment by AshD** [comment]
`  File "C:\AI\research\olive\olive\examples\directml\stable_diffusion\stable_diffusion_local2.py", line 304, in optimize
    unoptimized_olive_model = ONNXModelHandler(**conversion_footprint["model_config"]["config"])
KeyError: 'config'`

model_config is null below.

`{"bd3baafdee1ba8aa8535c88f59954127": {"parent_model_id": null, "model_id": "bd3baafdee1ba8aa8535c88f59954127", "model_config": null, "from_pass": null, "pass_run_config": null, "is_pareto_frontier": false, "metrics": null, "start_time": 0, "end_time": 0}, "1_OnnxConversion-bd3baafdee1ba8aa8535c88f59954127-c0506ab83b20c8664e9ca29fd4d895a5": {"parent_model_id": "bd3baafdee1ba8aa8535c88f59954127", "model_id": "1_OnnxConversion-bd3baafdee1ba8aa8535c88f59954127-c0506ab83b20c8664e9ca29fd4d895a5", "model_config": {"is_pruned": true}, "from_pass": "OnnxConversion", "pass_run_config": {"script_dir": null, "user_script": null, "target_opset": 14, "use_dynamo_exporter": false, "use_device": null, "torch_dtype": null, "parallel_jobs": null, "merge_components": false, "save_as_external_data": false, "all_tensors_to_one_file": true, "external_data_name": null, "size_threshold": 1024, "convert_attribute": false}, "is_pareto_frontier": false, "metrics": null, "start_time": 1704330673.66373, "end_time": 1704330673.764908}}`

**Comment by guotuofeng** [comment]
does the model conversion has any error message? are there any model file under cache/model/[Index]-OnnxConversion-[hash]/output_model?

**Comment by AshD** [comment]
This weird. I changed my code to reload the model after saving it in the pytorch format. And it **worked**!

```
    pipeline = StableDiffusionPipeline.from_single_file("./models/ghostmix_v20Bakedvae.safetensors", torch_dtype=torch.float16).to("cuda")
    pipeline.save_pretrained(model_id,False)

    pipeline = DiffusionPipeline.from_pretrained(model_id)
```

**Comment by AshD** [comment]
Thanks Mike for your help. Closing the issue from my side since it is working now.
