### ISSUE TITLE
Some parameters is removed in latest version conversion

### ISSUE THREAD

**Issue by hwangdeyu** [microsoft/OLive#86]
A few reminders that might be useful.

Reference linking:
https://github.com/microsoft/OLive/blob/0b989430f62ba215132a61815df2cabd43a6f668/olive/conversion/pytorch_converter.py#L58
https://github.com/microsoft/OLive/blob/0b989430f62ba215132a61815df2cabd43a6f668/olive/conversion/tensorflow_converter.py#L39

PyTorch-ONNX was removed `example_outputs arg` from `torch.onnx.export` in [PyTorch 1.11 Release](https://github.com/pytorch/pytorch/releases?q=example_output&expanded=true).
TensorFlow-ONNX was removed `const_fold/fold_constant` in latest main branch. [PR](https://github.com/onnx/tensorflow-onnx/pull/1861)

**Comment by leqiao-1** [comment]
Fix in PR https://github.com/microsoft/OLive/pull/89
