### ISSUE TITLE
Error with search strategic.py 'Conversion Merged" has no output models for Llama2 optimization

### ISSUE THREAD

**Issue by FepeIMT** [microsoft/Olive#897]
**Describe the bug**
When is in process to convert to Onnx model this is interrumped by the log error 

**To Reproduce**
Follow instructions for llama2 Optmization (https://github.com/microsoft/Olive/tree/main/examples/llama2) after RUN the next command: 
run to optimize the model: FP32/INT8/INT4
python llama2.py --model_name meta-llama/Llama-2-7b-hf

**Expected behavior**
Complete process and get model quantified to INT8/INT4

**Olive config**
Last Olive version installed 

**Olive logs**
File "C:\...\Olive\strategy\search_strategy.py", line 182, in _next_search_group_pass_by_pass raise ValueError(
ValueError: The Previous search group ['conversion_merged'] has no output models that were created and evaluated successfully. Cannot  continue. 

**Other information**
 - OS: Windows10
 - Olive version: main
 - ONNXRuntime package and version: onnxruntime-gpu: 1.16.2

**Additional context**

**Comment by guotuofeng** [comment]
@FepeIMT, would you please provide the full logs so that we can take a look?

**Comment by FepeIMT** [comment]
I just solved this issue by increasing the RAM (MemoryError) of my system from 32 to 48 GB. Thanks for your response.
