### ISSUE TITLE
NOT_IMPLEMENTED : Could not find an implementation for BeamSearch(1) node with name 'BeamSearch_node'

### ISSUE THREAD

**Issue by HKAB** [microsoft/Olive#900]
I'm trying to export Whisper from [here](https://github.com/microsoft/Olive/tree/main/examples/whisper).  

Pipeline: *GPU, FP16: PyTorch Model -> Onnx Model -> Transformers Optimized Onnx Model -> Mixed Precision Model -> Insert Beam Search Op -> Insert Pre/Post Processing Ops*

 using olive in the `main` branch and `onnxruntime-gpu-1.16.3`

Step:
```bash
python prepare_whisper_configs.py --model_name openai/whisper-tiny.en --atol 1e-4
python -m olive.workflows.run --config whisper_gpu_fp16.json
```
which yield the error:
```
.......
File "/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 463, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for BeamSearch(1) node with name 'BeamSearch_node'
[2024-01-25 09:17:41,782] [INFO] [engine.py:282:run] Run history for gpu-cuda:
[2024-01-25 09:17:41,783] [INFO] [engine.py:557:dump_run_history] Please install tabulate for better run history output
[2024-01-25 09:17:41,783] [INFO] [engine.py:296:run] No packaging config provided, skip packaging artifacts
```

However, when I try with `python -m olive.workflows.run --config whisper_cpu_fp32.json`, it works. Is the Beam Search Op export with GPU is not support right now? Thank you.

**Comment by guotuofeng** [comment]
@jambayk, do you have any insight on this error? do we hit it before?

**Comment by HKAB** [comment]
My `pip list | grep onnx` yields:

```
onnx                      1.15.0
onnxruntime-extensions    0.9.0
onnxruntime-gpu           1.16.3
```
and `pip list | grep ort` yields:

```
ort-nightly-gpu           1.15.0.dev20230502003
```

I deleted the `cache` folder, but it still not works. I saw an error in the middle of the logs:

```
[E:onnxruntime:Default, provider_bridge_ort.cc:1480 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session
/provider_bridge_ort.cc:1193 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed 
to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory
```
Is this error relevant to my issue? Thank you.

**Comment by guotuofeng** [comment]
seems similar to https://stackoverflow.com/questions/70268140/could-not-load-dynamic-library-libcublaslt-so-11-dlerror-libcublaslt-so-11

**Comment by HKAB** [comment]
Thanks @guotuofeng. The problems might because of the `libcudart`. I was using docker `pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime`, wwitch to docker with Ubuntu like `anibali/pytorch:2.0.1-cuda11.8` solve the problem.
